#include "lesson_data.h"
#include "i18n.h"

static const LessonSpec LESSONS[] = {
    {
        .id = "overview.all",
        .slug = "overview.all",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Big Picture",
        .title_zh = "大致了解",
        .summary_en = "A map of Machine 2.0 syntax, directives, types, builtin families, and where each one is useful.",
        .summary_zh = "先整体看清 Machine 2.0 的语法、指令、类型、内建函数族，以及它们适合用在什么场景。",
        .notes_en = "Machine 2.0 is indentation-sensitive. Common top-level items are main:, func, struct, module, var, and const. Current major directives include bin.runtime, unsafe.enable, backend.c, backend.x86_64-asm, target.freestanding-x86_64, and target.baremetal-x86_64. Important type families include i64, f64, hp, str, bool, ptr, list, array, and user structs. Common builtin families include array_*, list_*, alloc_bytes/free_mem, load_*/store_*, volatile_load_*/volatile_store_*, ptr_offset/ptr_to_i64/ptr_from_i64, ptr_hex/ptr_bin, syscall*, fd_*, mmap_anon/munmap_mem, and some asm/cpu/apic helpers. Typical learning path: ordinary Linux output -> control flow -> functions and structs -> containers -> pointers and raw memory -> unsafe low-level access -> freestanding/baremetal experiments -> algorithm and benchmark challenges.",
        .notes_zh = "Machine 2.0 是缩进敏感语言。常见顶层项包括 main:、func、struct、module、var、const。当前重要指令包括 bin.runtime、unsafe.enable、backend.c、backend.x86_64-asm、target.freestanding-x86_64、target.baremetal-x86_64。核心类型族包括 i64、f64、hp、str、bool、ptr、list、array，以及用户自定义结构体。常见内建函数族包括 array_*、list_*、alloc_bytes/free_mem、load_*/store_*、volatile_load_*/volatile_store_*、ptr_offset/ptr_to_i64/ptr_from_i64、ptr_hex/ptr_bin、syscall*、fd_*、mmap_anon/munmap_mem，还有部分 asm/cpu/apic 辅助函数。推荐学习路径是：普通 Linux 输出 -> 控制流 -> 函数和结构体 -> 容器 -> 指针与原始内存 -> unsafe 底层访问 -> freestanding/baremetal 实验 -> 算法与性能挑战。",
        .headers_en = "Use the smallest correct directive set. Normal Linux programs often start with bin.runtime. Low-level raw memory often adds unsafe.enable. Freestanding and baremetal switch to target.* directives.",
        .headers_zh = "指令要遵循“最小正确集合”。普通 Linux 程序常从 bin.runtime 开始。底层原始内存场景通常再加 unsafe.enable。freestanding 与 baremetal 则切换到对应的 target.* 指令。",
        .goal_en = "Read this page once before the first lesson. Later nodes will repeatedly refer back to these directive, type, and builtin families.",
        .goal_zh = "在正式进第一关之前，先把这个总览页面过一遍。后面很多关卡都会反复回到这些指令、类型和 builtin 家族。",
        .example_code = "bin.runtime\nunsafe.enable\n\nstruct Pair:\n  a: i64\n  b: i64\n\nmodule MathBox:\n  func sum_pair(p: Pair) -> i64:\n    ret p.a + p.b\n\nmain:\n  var arr: array = array_new()\n  array_push(arr, 6)\n  print MathBox.sum_pair(Pair())\n  ret 0\n",
        .editor_default = "bin.runtime\n\nmain:\n  print \"Machine 2.0\"\n  ret 0\n",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "intro.overview",
        .slug = "intro.overview",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Start Here",
        .title_zh = "从这里开始",
        .summary_en = "Get comfortable with the layout before you start writing real Machine code.",
        .summary_zh = "先熟悉整个界面布局，再开始真正手写 Machine 代码。",
        .notes_en = "This page is your long-term Linux learning workspace for Machine. The left side is the lesson tree, the middle side is the teaching area, and the right side is the real .mne editor. When you revisit the app, it restores the node you last opened.",
        .notes_zh = "这个页面就是你长期使用的 Machine Linux 学习工作区。左侧是课程节点树，中间是教学说明区，右侧是真实的 .mne 编辑器。以后重新打开软件时，会自动回到你上次停留的节点。",
        .headers_en = "No precompiled header is required on this overview page.",
        .headers_zh = "这个总览页面不需要任何预编译头。",
        .goal_en = "Use the sidebar to move lesson by lesson. From String Output onward, each node becomes a hands-on task.",
        .goal_zh = "先用左侧节点一关一关往下学。从“字符串输出”开始，每一关都会进入真正的动手练习。",
        .example_code = "-- The editor on the right is real.\n-- Later lessons will save your code automatically.\n",
        .editor_default = "bin.runtime\n\nmain:\n  print \"Machine Learning\"\n  ret 0\n",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "syntax.machine_2",
        .slug = "syntax.machine_2",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Machine 2.0 Syntax",
        .title_zh = "Machine 2.0 语法",
        .summary_en = "The editor keeps `.mne` source plain and focuses on lesson flow, save/resume, and run feedback.",
        .summary_zh = "编辑器会保持 `.mne` 源码的纯文本显示，重点放在课程流程、自动保存和运行反馈上。",
        .notes_en = "Machine uses indentation-sensitive blocks. Top-level items commonly include main:, func, struct, module, var, and const. The editor on the right is not a fake preview: it is the surface you will use for real lessons.",
        .notes_zh = "Machine 使用缩进敏感的代码块。顶层通常会出现 main:、func、struct、module、var、const 等。右侧编辑器不是假预览，而是后面真正会让你写关卡代码的地方。",
        .headers_en = "Most basic lessons can compile without an explicit precompiled header. Some hosted Linux lessons intentionally use bin.runtime so beginners can remember the runtime mode clearly.",
        .headers_zh = "很多基础关卡即使不写预编译头也能编译。但有些 Linux hosted 教学关卡会刻意使用 bin.runtime，这样更方便初学者记住当前运行模式。",
        .goal_en = "Observe indentation, directives, built-in functions, and type names. You do not need to pass anything on this information page.",
        .goal_zh = "先观察缩进、头部指令、内建函数和类型名。这个信息页不要求你通过任何判定。",
        .example_code = "struct Pair:\n  left: i64\n  right: i64\n\nmodule MathBox:\n  func sum_pair(p: Pair) -> i64:\n    ret p.left + p.right\n",
        .editor_default = "bin.runtime\n\nmain:\n  print \"Syntax\"\n  ret 0\n",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "resume.database",
        .slug = "resume.database",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Resume & Database",
        .title_zh = "断点恢复与数据库",
        .summary_en = "Lesson progress, editor text, and your current node are stored in the SQLite database folder you chose.",
        .summary_zh = "课程进度、编辑器内容和当前节点都会保存到你自己选择的 SQLite 数据库目录里。",
        .notes_en = "This software stores lesson state in the database file and mirrors runnable .mne lesson files beside that database. If you delete the database directory later, onboarding will start again because there is no longer a saved state to restore.",
        .notes_zh = "本软件会把课程状态写进数据库文件，同时把可运行的 .mne 课程文件镜像保存到数据库旁边。如果你以后删掉了数据库目录，那么由于没有状态可恢复，程序就会重新进入首次引导。",
        .headers_en = "No extra precompiled header is needed for the resume system itself.",
        .headers_zh = "断点恢复系统本身不需要额外预编译头。",
        .goal_en = "Know where your code and executable files are mirrored before you start the hands-on nodes.",
        .goal_zh = "在正式开始动手关卡前，先知道你的代码文件和可执行文件会被镜像保存到哪里。",
        .example_code = "-- Example mirror files beside the database\n-- string_output.mne\n-- string_output_app\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "string.output",
        .slug = "string.output",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "String Output",
        .title_zh = "字符串输出",
        .summary_en = "Print your first exact line of text with Machine.",
        .summary_zh = "用 Machine 输出你的第一行精确文本。",
        .notes_en = "This is your first real output lesson. bin.runtime selects the hosted Linux runtime. main: is the entry block. print writes to standard output. ret 0 ends the program successfully. Keep the program small and clear.",
        .notes_zh = "这是你的第一关真正输出课程。bin.runtime 代表 hosted Linux 运行时。main: 是入口块。print 会把内容输出到标准输出。ret 0 表示程序正常结束。先把程序写得小而清楚。",
        .headers_en = "Precompiled headers for this lesson: bin.runtime",
        .headers_zh = "本关预编译头：bin.runtime",
        .goal_en = "Write a Machine program that prints exactly: Hello, Machine!",
        .goal_zh = "写一个 Machine 程序，并且让它准确输出：Hello, Machine!",
        .example_code = "bin.runtime\n\nmain:\n  -- print your target string here\n  -- remember to end the program cleanly\n",
        .editor_default = "",
        .expected_output = "Hello, Machine!",
        .required_tokens = {"bin.runtime", "main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "operators.math",
        .slug = "operators.math",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Operators",
        .title_zh = "运算符",
        .summary_en = "Use addition, subtraction, multiplication, and division in one lesson.",
        .summary_zh = "在同一关里同时用到加、减、乘、除。",
        .notes_en = "Arithmetic expressions in Machine are direct and readable. A good beginner habit is to store numbers in variables first, then print each result one by one. This helps you see exactly what each operator does.",
        .notes_zh = "Machine 的算术表达式写法很直接。对初学者来说，一个好习惯是先把数字放进变量，再逐行 print 每个结果。这样你能更清楚地看见每个运算符在做什么。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use +, -, *, and /. Make your program output exactly:\n25\n15\n100\n4",
        .goal_zh = "同时用到 +、-、*、/。让程序最终准确输出：\n25\n15\n100\n4",
        .example_code = "main:\n  var a: i64 = 20\n  var b: i64 = 5\n  print a + b\n  print a - b\n  -- still add multiplication, division, and ret 0\n",
        .editor_default = "",
        .expected_output = "25\n15\n100\n4",
        .required_tokens = {"+", "-", "*", "/", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "operators.compare",
        .slug = "operators.compare",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Comparison Operators",
        .title_zh = "比较运算",
        .summary_en = "Practice ==, !=, <, >, <=, and >= together.",
        .summary_zh = "把 ==、!=、<、>、<=、>= 一次练全。",
        .notes_en = "Comparison operators return boolean values in Machine. In the current compiler, printing a boolean directly produces 1 or 0. This lesson is about making each comparison expression appear explicitly in your own code.",
        .notes_zh = "比较运算会在 Machine 里得到布尔值。当前编译器里，直接 print 布尔值通常会显示成 1 或 0。这一关的重点是让这些比较表达式真正出现在你自己的代码里。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use all six comparison operators and output exactly:\n1\n1\n1\n1\n1\n1",
        .goal_zh = "用齐六个比较运算符，并让程序准确输出：\n1\n1\n1\n1\n1\n1",
        .example_code = "main:\n  print 5 == 5\n  print 5 != 4\n  print 3 < 9\n  -- still add >, <=, >=, and ret 0\n",
        .editor_default = "",
        .expected_output = "1\n1\n1\n1\n1\n1",
        .required_tokens = {"==", "!=", "<", ">", "<=", ">=", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "branch.ifelse",
        .slug = "branch.ifelse",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "If / Elif / Else",
        .title_zh = "条件分支",
        .summary_en = "Route different values through if, elif, and else.",
        .summary_zh = "通过 if、elif、else 让不同值走向不同分支。",
        .notes_en = "Machine uses indentation-sensitive branches. if checks the first condition. elif adds another condition if the first one failed. else is the final fallback. This lesson asks you to judge several values and print the results in order.",
        .notes_zh = "Machine 的分支也是缩进敏感的。if 先检查第一条条件。elif 在前面没成立时继续检查。else 是最后兜底。这一关要求你判断几种不同输入，并按顺序输出结果。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use if, elif, and else. Make the program output exactly:\n-1\n0\n1\n2",
        .goal_zh = "同时使用 if、elif、else，并让程序准确输出：\n-1\n0\n1\n2",
        .example_code = "func judge(x: i64) -> i64:\n  if x < 0:\n    ret -1\n  elif x == 0:\n    ret 0\n  -- still add another elif / else path\n\nmain:\n  print judge(-5)\n",
        .editor_default = "",
        .expected_output = "-1\n0\n1\n2",
        .required_tokens = {"func ", "if ", "elif ", "else:", "ret ", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "loop.while",
        .slug = "loop.while",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "While Loop",
        .title_zh = "while 循环",
        .summary_en = "Repeat work with while and a changing counter.",
        .summary_zh = "用 while 和变化中的计数器重复执行代码。",
        .notes_en = "A while loop keeps running as long as its condition stays true. The most common beginner pattern is a counter variable that you update inside the loop body. If you forget to update it, the loop may never stop.",
        .notes_zh = "只要条件还成立，while 循环就会继续执行。初学者最常见的写法是先准备一个计数变量，然后在循环体里不断更新它。如果忘了更新，这个循环就可能停不下来。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use while and make the program output exactly:\n0\n1\n2\n3\n4",
        .goal_zh = "使用 while，并让程序准确输出：\n0\n1\n2\n3\n4",
        .example_code = "main:\n  var i: i64 = 0\n  while i < 5:\n    print i\n    -- remember to increase i\n",
        .editor_default = "",
        .expected_output = "0\n1\n2\n3\n4",
        .required_tokens = {"while ", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "func.basic",
        .slug = "func.basic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Functions",
        .title_zh = "函数",
        .summary_en = "Return values from your own function and print them in main.",
        .summary_zh = "自己写函数返回值，再在 main 里打印。",
        .notes_en = "A function lets you package logic into a named reusable block. Parameters go inside parentheses. -> sets the return type. ret sends a value back to the caller.",
        .notes_zh = "函数可以把逻辑打包成一个有名字、可复用的块。参数写在括号里，-> 指定返回类型，ret 把值交回给调用者。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Write at least one function and make the program output exactly:\n7\n42",
        .goal_zh = "至少写一个函数，并让程序准确输出：\n7\n42",
        .example_code = "func add(a: i64, b: i64) -> i64:\n  ret a + b\n\nmain:\n  print add(3, 4)\n  -- still produce one more line and ret 0\n",
        .editor_default = "",
        .expected_output = "7\n42",
        .required_tokens = {"func ", "->", "ret ", "main:", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "struct.fields",
        .slug = "struct.fields",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Struct Fields",
        .title_zh = "结构体字段",
        .summary_en = "Create a struct, fill its fields, and read them back.",
        .summary_zh = "创建结构体，给字段赋值，再把字段读出来。",
        .notes_en = "A struct groups related data into one custom type. After constructing the struct value, you can assign to its fields with dot access.",
        .notes_zh = "结构体会把相关数据打包成一个自定义类型。创建结构体值以后，你就可以通过点号给字段赋值。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use struct and field access. Make the program output exactly:\n13\n42",
        .goal_zh = "使用 struct 和字段访问，并让程序准确输出：\n13\n42",
        .example_code = "struct Pair:\n  a: i64\n  b: i64\n\nmain:\n  var p = Pair()\n  p.a = 6\n  -- still assign p.b, print results, and ret 0\n",
        .editor_default = "",
        .expected_output = "13\n42",
        .required_tokens = {"struct ", ".", "Pair()", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "module.basic",
        .slug = "module.basic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Modules",
        .title_zh = "模块",
        .summary_en = "Call functions through a module name and dot access.",
        .summary_zh = "通过模块名和点号调用函数。",
        .notes_en = "A module is useful for grouping related functions. Instead of calling sum_pair directly, you call MathBox.sum_pair.",
        .notes_zh = "模块很适合把相关函数分组。你不是直接调用 sum_pair，而是调用 MathBox.sum_pair。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use module and function calls through the module name. Output exactly:\n13\n42",
        .goal_zh = "使用 module，并通过模块名调用函数。最终准确输出：\n13\n42",
        .example_code = "struct Pair:\n  a: i64\n  b: i64\n\nmodule MathBox:\n  func sum_pair(p: Pair) -> i64:\n    ret p.a + p.b\n\nmain:\n  var p = Pair()\n  -- still finish the second function, assign values, print, and ret 0\n",
        .editor_default = "",
        .expected_output = "13\n42",
        .required_tokens = {"module ", "func ", ".", "ret ", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "array.dynamic",
        .slug = "array.dynamic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Dynamic Array",
        .title_zh = "动态数组",
        .summary_en = "Push values into array, read them back, and free the container.",
        .summary_zh = "把值压入动态数组，再读出来，最后释放容器。",
        .notes_en = "Create with array_new, append with array_push, inspect with array_len and array_get, and release with array_free.",
        .notes_zh = "用 array_new 创建，用 array_push 追加，用 array_len 和 array_get 读取，最后用 array_free 释放。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use dynamic array helpers and output exactly:\n3\n20",
        .goal_zh = "使用动态数组相关辅助函数，并让程序准确输出：\n3\n20",
        .example_code = "main:\n  var arr: array = array_new()\n  array_push(arr, 10)\n  array_push(arr, 20)\n  array_push(arr, 30)\n  print array_len(arr)\n  -- still print one selected element, free the array, and ret 0\n",
        .editor_default = "",
        .expected_output = "3\n20",
        .required_tokens = {"array_new", "array_push", "array_len", "array_get", "array_free", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "list.basic",
        .slug = "list.basic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "List",
        .title_zh = "链表容器",
        .summary_en = "Use list_new, list_push_back, and list_get in a small container exercise.",
        .summary_zh = "用 list_new、list_push_back、list_get 完成一个小容器练习。",
        .notes_en = "The built-in list helpers give you a simpler entry point than writing a linked list implementation by hand on day one.",
        .notes_zh = "内建 list 辅助函数，能让你先从“会用容器”开始，而不是一上来就手写链表实现。",
        .headers_en = "Precompiled headers for this lesson: none required.",
        .headers_zh = "本关预编译头：不需要。",
        .goal_en = "Use list helpers and output exactly:\n3\n22",
        .goal_zh = "使用 list 辅助函数，并让程序准确输出：\n3\n22",
        .example_code = "main:\n  var xs: list = list_new()\n  list_push_back(xs, 11)\n  list_push_back(xs, 22)\n  list_push_back(xs, 33)\n  print list_size(xs)\n  -- still read one element, free the list, and ret 0\n",
        .editor_default = "",
        .expected_output = "3\n22",
        .required_tokens = {"list_new", "list_push_back", "list_size", "list_get", "list_free", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "pointer.basic",
        .slug = "pointer.basic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Pointers",
        .title_zh = "指针",
        .summary_en = "Touch address-of, dereference, raw memory allocation, store, load, and free.",
        .summary_zh = "练到取地址、解引用、原始内存申请、写入、读取和释放。",
        .notes_en = "@x takes the address of x. p^ dereferences a pointer. alloc_bytes reserves raw memory, store_i64 writes a value there, load_i64 reads it back, and free_mem releases the block.",
        .notes_zh = "@x 用来取得 x 的地址，p^ 用来解引用指针。alloc_bytes 申请原始内存，store_i64 往里面写值，load_i64 把值读出来，free_mem 释放这块内存。",
        .headers_en = "Current hosted lesson setup: no extra directive required for this pointer exercise.",
        .headers_zh = "按当前 hosted 练习写法，本关不需要额外指令。",
        .goal_en = "Use pointers and memory helpers. Output exactly:\n10\n99\n12345",
        .goal_zh = "使用指针和内存辅助函数，并让程序准确输出：\n10\n99\n12345",
        .example_code = "main:\n  var x: i64 = 10\n  var p: ptr = @x\n  print x\n  p^ = 99\n  -- still print the changed value, allocate memory, store, load, free, and ret 0\n",
        .editor_default = "",
        .expected_output = "10\n99\n12345",
        .required_tokens = {"@", "^", "alloc_bytes", "store_i64", "load_i64", "free_mem", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "pointer.memory",
        .slug = "pointer.memory",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Pointer Memory Access",
        .title_zh = "指针访问内存与操作",
        .summary_en = "Walk raw memory with ptr_offset and read/write multiple slots.",
        .summary_zh = "用 ptr_offset 在原始内存上走位，并读写多个槽位。",
        .notes_en = "This lesson focuses on pointer stepping. Reserve one block, move by 8-byte offsets, store values into several locations, read them back, and free the block. In the current Machine 2.0 build, ptr_offset must not only have unsafe.enable at the top: every ptr_offset call also needs to appear inside an unsafe: block.",
        .notes_zh = "这一关强调指针偏移。先申请一块内存，再按 8 字节偏移走到不同位置，分别写入、读取，最后释放。按当前 Machine 2.0 真实规则，ptr_offset 不只是需要文件头里的 unsafe.enable；凡是调用 ptr_offset 的地方，还必须写在 unsafe: 代码块里面。",
        .headers_en = "Required directives for this lesson: bin.runtime and unsafe.enable. Also place every ptr_offset use inside an unsafe: block.",
        .headers_zh = "本关必须写：bin.runtime 和 unsafe.enable；并且每一个 ptr_offset 调用都必须放进 unsafe: 块里。",
        .goal_en = "Use alloc_bytes, ptr_offset, store_i64, and load_i64. Output exactly:\n11\n22\n33",
        .goal_zh = "使用 alloc_bytes、ptr_offset、store_i64、load_i64。最终准确输出：\n11\n22\n33",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  var mem: ptr = alloc_bytes(24)\n  store_i64(mem, 11)\n  unsafe:\n    store_i64(ptr_offset(mem, 8), 22)\n    -- still store one more value and print the offset-based reads here\n  free_mem(mem)\n  ret 0\n",
        .editor_default = "",
        .expected_output = "11\n22\n33",
        .required_tokens = {"bin.runtime", "unsafe.enable", "unsafe:", "alloc_bytes", "ptr_offset", "store_i64", "load_i64", "free_mem", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "operators.special",
        .slug = "operators.special",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Special Access Operators",
        .title_zh = "特殊访问表达式",
        .summary_en = "Practice address-of, dereference, field access, and indexing together.",
        .summary_zh = "把取地址、解引用、字段访问、下标访问放在同一关里练。",
        .notes_en = "This lesson focuses on non-arithmetic operator forms. You will read a const table with [], read/write through a pointer with @ and ^, and access a struct field with dot syntax.",
        .notes_zh = "这一关专门练“不是加减乘除”的表达式形式。你会用 [] 读常量表、用 @ 和 ^ 进行指针读写，再用点号访问结构体字段。",
        .headers_en = "No special directive is required for this hosted exercise.",
        .headers_zh = "这个 hosted 练习不需要额外指令。",
        .goal_en = "Use @, ^, ., and []. Output exactly:\n7\n6\n9",
        .goal_zh = "同时用到 @、^、.、[]。最终准确输出：\n7\n6\n9",
        .example_code = "const XS = [3, 6, 9]\n\nstruct Box:\n  value: i64\n\nmain:\n  var x: i64 = 7\n  var p: ptr = @x\n  var b = Box()\n  b.value = XS[1]\n  -- still print p^, b.value, XS[2], and ret 0\n",
        .editor_default = "",
        .expected_output = "7\n6\n9",
        .required_tokens = {"@", "^", ".", "[", "]", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "goto.basic",
        .slug = "goto.basic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "goto",
        .title_zh = "goto",
        .summary_en = "Use label and goto deliberately in one small control-flow exercise.",
        .summary_zh = "在一个小控制流练习里刻意使用 label 和 goto。",
        .notes_en = "Machine supports label name: and goto name. Labels must be indented inside the surrounding block; they are statements, not top-level items. Use them sparingly. The point of this lesson is to understand what direct jumps look like, not to replace structured control flow everywhere.",
        .notes_zh = "Machine 支持 label 名称: 和 goto 名称。注意：label 必须缩进在所在代码块内部，它本身是语句，不是顶层项。这个能力要谨慎使用。这一关的重点是看懂“直接跳转”长什么样，而不是到处拿它替代结构化控制流。",
        .headers_en = "Use the default hosted mode. The C backend currently handles goto better than the asm backend for this lesson.",
        .headers_zh = "本关使用默认 hosted 模式即可。对这关来说，C 后端比 asm 后端更适合。",
        .goal_en = "Use at least one label and one goto. Output exactly:\n0\n1\n2\n99",
        .goal_zh = "至少使用一个 label 和一个 goto，并让程序准确输出：\n0\n1\n2\n99",
        .example_code = "main:\n  var i: i64 = 0\n  label loop:\n  print i\n  i = i + 1\n  if i < 3:\n    goto loop\n  goto done\n  label done:\n  -- still print 99 and ret 0\n",
        .editor_default = "",
        .expected_output = "0\n1\n2\n99",
        .required_tokens = {"label ", "goto ", "if ", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "pointer.smart",
        .slug = "pointer.smart",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Smart Pointer Pattern",
        .title_zh = "智能指针",
        .summary_en = "Build a teaching pattern around ptr inside a struct. This is a pattern lesson, not a dedicated Machine keyword.",
        .summary_zh = "用结构体把 ptr 包起来，做一个“教学型智能指针模式”。这不是 Machine 的专门关键字，而是课程模式。",
        .notes_en = "Machine 2.0 does not currently have a dedicated smart pointer keyword. This lesson teaches a user-space pattern: store ptr inside a struct, initialize it in one place, read it through helper functions, and free it explicitly.",
        .notes_zh = "Machine 2.0 当前没有专门的“智能指针”关键字。本关教的是用户层模式：把 ptr 放进结构体，在固定入口里初始化，通过辅助函数读取，并明确地释放。",
        .headers_en = "Recommended directives: bin.runtime, plus unsafe.enable if you want your lesson code to visibly mark low-level sections.",
        .headers_zh = "推荐指令：bin.runtime；如果你想让低层操作显式可见，也可以加 unsafe.enable。",
        .goal_en = "Build a small ptr wrapper pattern and output exactly:\n77",
        .goal_zh = "做一个小型 ptr 包装模式，并准确输出：\n77",
        .example_code = "struct SmartBox:\n  mem: ptr\n\nfunc smart_new(v: i64) -> SmartBox:\n  var box = SmartBox()\n  box.mem = alloc_bytes(8)\n  -- still store v and return the box\n\nmain:\n  -- still create one SmartBox, read the value, free it, and ret 0\n",
        .editor_default = "",
        .expected_output = "77",
        .required_tokens = {"struct SmartBox", "ptr", "alloc_bytes", "store_i64", "load_i64", "free_mem", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "pointer.offset",
        .slug = "pointer.offset",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Offset Pointers",
        .title_zh = "偏移指针",
        .summary_en = "Use ptr_offset to compare and inspect addresses.",
        .summary_zh = "用 ptr_offset 做地址偏移、比较和观察。",
        .notes_en = "ptr_offset does not allocate anything by itself. It simply returns another pointer derived from the original address plus an offset. This is perfect for layout experiments.",
        .notes_zh = "ptr_offset 自己不会申请内存。它只是从原地址出发，加上一个偏移量后返回另一个指针。这很适合做布局实验。",
        .headers_en = "Recommended directives: bin.runtime and unsafe.enable.",
        .headers_zh = "推荐指令：bin.runtime 和 unsafe.enable。",
        .goal_en = "Use ptr_offset and ptr_to_i64. Output exactly:\n1\n1",
        .goal_zh = "使用 ptr_offset 和 ptr_to_i64。准确输出：\n1\n1",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  unsafe:\n    var mem: ptr = alloc_bytes(16)\n    print ptr_to_i64(ptr_offset(mem, 8)) > ptr_to_i64(mem)\n    -- still compare one more offset, free memory, and ret 0\n",
        .editor_default = "",
        .expected_output = "1\n1",
        .required_tokens = {"unsafe.enable", "ptr_offset", "ptr_to_i64", "alloc_bytes", "free_mem", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "const.table1d",
        .slug = "const.table1d",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "One-Dimensional Constant Table",
        .title_zh = "一维常量表",
        .summary_en = "Read values from a one-dimensional const literal table.",
        .summary_zh = "从一维 const 字面量表里读取值。",
        .notes_en = "A constant table lets you keep read-only data close to the top of the file. This lesson is about declaration shape and indexing.",
        .notes_zh = "常量表可以让你把只读数据放在文件顶部。这一关的重点是声明形状和索引读取。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Use a one-dimensional const table. Output exactly:\n4\n6",
        .goal_zh = "使用一维常量表，并准确输出：\n4\n6",
        .example_code = "const XS = [2, 4, 6, 8]\n\nmain:\n  print XS[1]\n  -- still print another value and ret 0\n",
        .editor_default = "",
        .expected_output = "4\n6",
        .required_tokens = {"const ", "[", "]", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "const.table2d",
        .slug = "const.table2d",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Two-Dimensional Constant Table",
        .title_zh = "二维常量表",
        .summary_en = "Read a nested constant table with two indexes.",
        .summary_zh = "用两个下标读取二维常量表。",
        .notes_en = "Nested const literals are useful for grids and lookup tables. Keep the brackets visually aligned so the shape stays obvious.",
        .notes_zh = "嵌套 const 字面量很适合做网格和查表数据。把括号排整齐，会更容易看清整体结构。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Use a two-dimensional const table. Output exactly:\n10\n60\n80",
        .goal_zh = "使用二维常量表，并准确输出：\n10\n60\n80",
        .example_code = "const TABLE = [\n  [10, 20, 30],\n  [40, 50, 60],\n  [70, 80, 90]\n]\n\nmain:\n  print TABLE[0][0]\n  -- still print two more values and ret 0\n",
        .editor_default = "",
        .expected_output = "10\n60\n80",
        .required_tokens = {"const TABLE", "[", "[", "]", "]", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "const.table3d",
        .slug = "const.table3d",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Three-Dimensional Constant Table",
        .title_zh = "三维常量表",
        .summary_en = "Read a cube-style constant literal with three indexes.",
        .summary_zh = "用三个下标读取立方体风格的常量字面量。",
        .notes_en = "Three-dimensional tables are harder to read at a glance, so indentation and line breaks matter even more here.",
        .notes_zh = "三维表比二维更难一眼看清，所以这一关对缩进和换行更敏感。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Use a three-dimensional const table. Output exactly:\n3\n6\n8",
        .goal_zh = "使用三维常量表，并准确输出：\n3\n6\n8",
        .example_code = "const CUBE = [\n  [\n    [1, 2],\n    [3, 4]\n  ],\n  [\n    [5, 6],\n    [7, 8]\n  ]\n]\n\nmain:\n  print CUBE[0][1][0]\n  -- still print two more values and ret 0\n",
        .editor_default = "",
        .expected_output = "3\n6\n8",
        .required_tokens = {"const CUBE", "[", "[", "[", "]", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "const.table_nested",
        .slug = "const.table_nested",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Multiline Nested Constant Literals",
        .title_zh = "多行嵌套常量字面量",
        .summary_en = "Practice writing multiline nested const literals cleanly.",
        .summary_zh = "专门练多行嵌套 const 字面量的排版与读取。",
        .notes_en = "This lesson is less about new syntax and more about writing nested literal shapes clearly enough that you can still reason about them later.",
        .notes_zh = "这一关不完全是新语法，而是专门训练你把多层字面量写得足够清楚，后面还能一眼读懂。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Build a multiline nested const literal and output exactly:\n1\n5\n8",
        .goal_zh = "写出多行嵌套常量字面量，并准确输出：\n1\n5\n8",
        .example_code = "const GRID = [\n  [1, 2],\n  [3, 4]\n]\n\nconst BLOCK = [\n  [\n    [5, 6],\n    [7, 8]\n  ]\n]\n\nmain:\n  print GRID[0][0]\n  -- still print BLOCK values and ret 0\n",
        .editor_default = "",
        .expected_output = "1\n5\n8",
        .required_tokens = {"const ", "[", "]", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "type.f64",
        .slug = "type.f64",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "f64",
        .title_zh = "f64",
        .summary_en = "Declare and print floating-point values.",
        .summary_zh = "声明并输出浮点数值。",
        .notes_en = "This lesson introduces the f64 type. Keep the arithmetic simple and focus on declaration, assignment, and visible output.",
        .notes_zh = "这一关专门引入 f64 类型。先把算术保持简单，重点看声明、赋值和输出。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Use f64 and make the output include 3.75 and 0.5.",
        .goal_zh = "使用 f64，并让输出里包含 3.75 和 0.5。",
        .example_code = "main:\n  var x: f64 = 1.5\n  var y: f64 = 2.25\n  print x + y\n  -- still print another f64 result and ret 0\n",
        .editor_default = "",
        .expected_output = "3.75\n0.5",
        .required_tokens = {"f64", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "type.str",
        .slug = "type.str",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "str",
        .title_zh = "str",
        .summary_en = "Declare string variables and print them clearly.",
        .summary_zh = "声明字符串变量，并把它们清楚地打印出来。",
        .notes_en = "This lesson focuses on the str type itself, not advanced string processing. Use one or two variables, print them, and keep the shape simple.",
        .notes_zh = "这一关重点是 str 类型本身，而不是复杂字符串处理。先准备一两个变量，print 出来，把代码形状写清楚。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Use str and output exactly:\nMachine\nHello, str",
        .goal_zh = "使用 str，并准确输出：\nMachine\nHello, str",
        .example_code = "main:\n  var name: str = \"Machine\"\n  print name\n  -- still print one more string and ret 0\n",
        .editor_default = "",
        .expected_output = "Machine\nHello, str",
        .required_tokens = {"str", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "type.bool",
        .slug = "type.bool",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NONE,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "bool",
        .title_zh = "bool",
        .summary_en = "Work with true and false directly.",
        .summary_zh = "直接使用 true 和 false。",
        .notes_en = "A bool is either true or false. In the current compiler path, printing bool commonly shows up as 1 or 0.",
        .notes_zh = "bool 只有 true 或 false 两种状态。按当前编译器路径，直接 print bool 时通常会显示成 1 或 0。",
        .headers_en = "No extra directive required.",
        .headers_zh = "不需要额外指令。",
        .goal_en = "Use bool values and output exactly:\n1\n0\n1",
        .goal_zh = "使用 bool 值，并准确输出：\n1\n0\n1",
        .example_code = "main:\n  var a: bool = true\n  var b: bool = false\n  print a\n  print b\n  -- still print one more bool expression and ret 0\n",
        .editor_default = "",
        .expected_output = "1\n0\n1",
        .required_tokens = {"bool", "true", "false", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "type.ptr",
        .slug = "type.ptr",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "ptr",
        .title_zh = "ptr",
        .summary_en = "Focus on the ptr type and conversions around it.",
        .summary_zh = "专门看 ptr 类型，以及围绕它的转换。",
        .notes_en = "ptr is the raw pointer type. This lesson focuses on declaring ptr values, getting one with @, and converting addresses with ptr_to_i64 or ptr_from_i64. In the current Machine 2.0 compiler, ptr_to_i64 and ptr_from_i64 require unsafe.enable.",
        .notes_zh = "ptr 是原始指针类型。本关重点是声明 ptr、用 @ 拿到地址，再用 ptr_to_i64 或 ptr_from_i64 做地址转换。按当前 Machine 2.0 编译器规则，ptr_to_i64 和 ptr_from_i64 需要 unsafe.enable。",
        .headers_en = "Required directives for this lesson: unsafe.enable. bin.runtime is optional here, but unsafe.enable is not.",
        .headers_zh = "本关必须写：unsafe.enable。bin.runtime 在这关不是必需，但 unsafe.enable 是必需的。",
        .goal_en = "Use ptr, ptr_to_i64, and ptr_from_i64. Output exactly:\n1\n1",
        .goal_zh = "使用 ptr、ptr_to_i64、ptr_from_i64。准确输出：\n1\n1",
        .example_code = "unsafe.enable\n\nmain:\n  var x: i64 = 7\n  var p: ptr = @x\n  print ptr_to_i64(p) > 0\n  -- still convert through ptr_from_i64 and ret 0\n",
        .editor_default = "",
        .expected_output = "1\n1",
        .required_tokens = {"unsafe.enable", "ptr", "@", "ptr_to_i64", "ptr_from_i64", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "pointer.bin",
        .slug = "pointer.bin",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Memory Address Binary",
        .title_zh = "内存地址二进制",
        .summary_en = "Render pointer addresses with ptr_bin for inspection.",
        .summary_zh = "用 ptr_bin 以二进制形式显示地址。",
        .notes_en = "ptr_bin returns a string representation of a pointer address. Because addresses vary per run, this lesson checks the syntax you used rather than one fixed output text.",
        .notes_zh = "ptr_bin 会返回一个指针地址的二进制字符串。由于地址每次运行都可能不同，这一关主要检查你是否真正写出了对应语法，而不是固定字符串。",
        .headers_en = "Recommended directives: bin.runtime and unsafe.enable, with the actual call placed inside unsafe:.",
        .headers_zh = "推荐指令：bin.runtime 和 unsafe.enable，并把真正调用放进 unsafe: 块里。",
        .goal_en = "Use ptr_bin with a real pointer and make the program compile and run successfully.",
        .goal_zh = "对真实指针使用 ptr_bin，并让程序顺利编译运行。",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  var x: i64 = 123\n  unsafe:\n    print ptr_bin(@x)\n  ret 0\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {"bin.runtime", "unsafe.enable", "unsafe:", "ptr_bin", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "pointer.hex",
        .slug = "pointer.hex",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Memory Address Hex",
        .title_zh = "内存地址十六进制",
        .summary_en = "Render pointer addresses with ptr_hex for inspection.",
        .summary_zh = "用 ptr_hex 以十六进制形式显示地址。",
        .notes_en = "ptr_hex is often the more readable first choice for address inspection. Like ptr_bin, the exact value changes between runs, so this lesson focuses on syntax and successful execution.",
        .notes_zh = "在地址观察里，ptr_hex 往往是更容易先读懂的第一选择。和 ptr_bin 一样，地址值每次运行都可能不同，所以这关重点是语法和成功运行。",
        .headers_en = "Recommended directives: bin.runtime and unsafe.enable, with ptr_hex used inside unsafe:.",
        .headers_zh = "推荐指令：bin.runtime 和 unsafe.enable，并在 unsafe: 块里使用 ptr_hex。",
        .goal_en = "Use ptr_hex with a real pointer and make the program compile and run successfully.",
        .goal_zh = "对真实指针使用 ptr_hex，并让程序顺利编译运行。",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  var x: i64 = 123\n  unsafe:\n    print ptr_hex(@x)\n  ret 0\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {"bin.runtime", "unsafe.enable", "unsafe:", "ptr_hex", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "switch.basic",
        .slug = "switch.basic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "switch",
        .title_zh = "switch",
        .summary_en = "Use switch, case, and default with i64 or bool values.",
        .summary_zh = "使用 switch、case、default 处理 i64 或 bool 值。",
        .notes_en = "Machine currently supports switch over i64 and bool expressions. Write the switch header with a colon, then add indented case and default blocks.",
        .notes_zh = "Machine 当前支持对 i64 和 bool 表达式做 switch。写 switch 头部后加冒号，再写缩进的 case 和 default 代码块。",
        .headers_en = "Use the default C backend for this lesson. The asm backend currently does not support switch.",
        .headers_zh = "这关请使用默认 C 后端。当前 asm 后端还不支持 switch。",
        .goal_en = "Use switch, case, and default. Output exactly:\ntwo\nother",
        .goal_zh = "使用 switch、case、default，并准确输出：\ntwo\nother",
        .example_code = "main:\n  var x: i64 = 2\n  switch x:\n    case 1:\n      print \"one\"\n    case 2:\n      print \"two\"\n    default:\n      print \"other\"\n  -- still add a second switch or path and ret 0\n",
        .editor_default = "",
        .expected_output = "two\nother",
        .required_tokens = {"switch ", "case ", "default", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "unsafe.volatile",
        .slug = "unsafe.volatile",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_NORMAL,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Volatile Memory",
        .title_zh = "特殊运算",
        .summary_en = "Use unsafe, mmap, and volatile load/store in one low-level Linux lesson.",
        .summary_zh = "在一个 Linux 底层练习里同时使用 unsafe、mmap、volatile 读写。",
        .notes_en = "This lesson demonstrates a more low-level Linux path: reserve memory with mmap_anon, write with volatile_store_u32, read with volatile_load_u32, and release with munmap_mem.",
        .notes_zh = "这一关演示更底层的 Linux 路线：用 mmap_anon 申请内存，用 volatile_store_u32 写入，再用 volatile_load_u32 读取，最后用 munmap_mem 释放。",
        .headers_en = "Recommended directives: bin.runtime and unsafe.enable.",
        .headers_zh = "推荐指令：bin.runtime 和 unsafe.enable。",
        .goal_en = "Use mmap_anon, volatile_store_u32, volatile_load_u32, and munmap_mem. Output exactly:\n305419896\n1",
        .goal_zh = "使用 mmap_anon、volatile_store_u32、volatile_load_u32、munmap_mem。准确输出：\n305419896\n1",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  unsafe:\n    var mem: ptr = mmap_anon(16)\n    volatile_store_u32(mem, 305419896)\n    print volatile_load_u32(mem)\n    -- still compare addresses or values, munmap, and ret 0\n",
        .editor_default = "",
        .expected_output = "305419896\n1",
        .required_tokens = {"bin.runtime", "unsafe.enable", "mmap_anon", "volatile_store_u32", "volatile_load_u32", "munmap_mem", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "syscall.linux",
        .slug = "syscall.linux",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "syscall",
        .title_zh = "syscall",
        .summary_en = "Touch a real Linux syscall from Machine.",
        .summary_zh = "从 Machine 里真正碰一次 Linux syscall。",
        .notes_en = "This is intentionally much closer to the system boundary. The simplest safe demonstration is syscall0(39) on x86_64 Linux, which returns the current process ID.",
        .notes_zh = "这一关会明显更贴近系统边界。对 x86_64 Linux 来说，最简单且相对安全的演示是 syscall0(39)，它会返回当前进程 ID。",
        .headers_en = "Recommended directives: bin.runtime and unsafe.enable.",
        .headers_zh = "推荐指令：bin.runtime 和 unsafe.enable。",
        .goal_en = "Use syscall0 and output exactly:\n1",
        .goal_zh = "使用 syscall0，并准确输出：\n1",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  unsafe:\n    var pid: i64 = syscall0(39)\n    print pid > 0\n  ret 0\n",
        .editor_default = "",
        .expected_output = "1",
        .required_tokens = {"bin.runtime", "unsafe.enable", "syscall0", "unsafe:", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "target.freestanding",
        .slug = "target.freestanding",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Freestanding Target",
        .title_zh = "freestanding 目标",
        .summary_en = "See how Machine switches from normal Linux hosting to freestanding mode.",
        .summary_zh = "看 Machine 如何从普通 Linux hosted 切到 freestanding 模式。",
        .notes_en = "Freestanding mode is for environments that are not ordinary hosted Linux processes. You usually pair target.freestanding-x86_64 with backend.x86_64-asm and a different runtime expectation.",
        .notes_zh = "freestanding 模式适合“不是普通 hosted Linux 进程”的环境。通常会把 target.freestanding-x86_64 和 backend.x86_64-asm 搭配起来，同时也意味着运行时预期发生变化。",
        .headers_en = "Typical directive set: unsafe.enable, backend.x86_64-asm, target.freestanding-x86_64",
        .headers_zh = "典型指令组合：unsafe.enable、backend.x86_64-asm、target.freestanding-x86_64",
        .goal_en = "Read this node before you step into boot, VGA, or lower-level experiments.",
        .goal_zh = "在进入 boot、VGA 或更底层实验之前，先把这张卡片看清楚。",
        .example_code = "unsafe.enable\nbackend.x86_64-asm\ntarget.freestanding-x86_64\n\nmain:\n  print \"freestanding\"\n  ret 0\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "target.baremetal",
        .slug = "target.baremetal",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Baremetal Target",
        .title_zh = "baremetal 目标",
        .summary_en = "Understand the directive set for true baremetal output.",
        .summary_zh = "理解真正 baremetal 输出需要的指令组合。",
        .notes_en = "Baremetal output is not a normal hosted Linux executable. It targets a boot-time or hardware-near environment, so you must not treat it like an ordinary desktop program.",
        .notes_zh = "baremetal 产物不是普通的 hosted Linux 可执行文件。它面向启动期或更靠近硬件的环境，所以不能把它当作普通桌面程序来运行。",
        .headers_en = "Typical directive set: unsafe.enable, backend.x86_64-asm, target.baremetal-x86_64",
        .headers_zh = "典型指令组合：unsafe.enable、backend.x86_64-asm、target.baremetal-x86_64",
        .goal_en = "Understand when baremetal is appropriate and why it is a different target class.",
        .goal_zh = "理解 baremetal 适合什么场景，以及为什么它属于完全不同的目标类型。",
        .example_code = "unsafe.enable\nbackend.x86_64-asm\ntarget.baremetal-x86_64\n\nmain:\n  print \"baremetal hello\"\n  ret 0\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "vga.lab",
        .slug = "vga.lab",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "VGA Memory Lab",
        .title_zh = "VGA 显存实验场景",
        .summary_en = "A high-difficulty card for direct VGA text memory experiments.",
        .summary_zh = "一个高难度的 VGA 文本显存直写实验卡片。",
        .notes_en = "This node is a lab card rather than an auto-judged hosted challenge. It discusses the classic text buffer area and why volatile store helpers matter in hardware-near experiments.",
        .notes_zh = "这一节点目前更像“实验说明卡”，而不是自动判定的 hosted 挑战。它主要讲经典文本显存区域，以及为什么在靠近硬件的实验里要使用 volatile 写入。",
        .headers_en = "Typical directive set: unsafe.enable, backend.x86_64-asm, target.baremetal-x86_64",
        .headers_zh = "典型指令组合：unsafe.enable、backend.x86_64-asm、target.baremetal-x86_64",
        .goal_en = "Use this card as the conceptual bridge before you test direct VGA writes in your own environment.",
        .goal_zh = "把这张卡当成概念桥梁，之后再在你自己的环境里测试真正的 VGA 直写。",
        .example_code = "unsafe.enable\nbackend.x86_64-asm\ntarget.baremetal-x86_64\n\nmain:\n  unsafe:\n    var text: ptr = ptr_from_i64(753664)\n    volatile_store_u16(text, 8013)\n  ret 0\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "qemu.boot",
        .slug = "qemu.boot",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "QEMU / Boot",
        .title_zh = "qemu / boot",
        .summary_en = "An ultra-hard card about boot images, emulation, and why the runtime target matters.",
        .summary_zh = "一个超难卡片，讲 boot 镜像、模拟器，以及为什么 runtime 目标真的会改变一切。",
        .notes_en = "Boot chains, emulators, and target-specific artifacts require their own workflow. This node is intentionally explanatory in the current build because hosted auto-judging is not the right model for boot testing.",
        .notes_zh = "boot 链路、模拟器和目标专属产物，需要单独的一套工作流。当前版本里，这个节点刻意以说明为主，因为 hosted 自动判定并不适合 boot 测试。",
        .headers_en = "Typical direction: backend.x86_64-asm plus target.freestanding-x86_64 or target.baremetal-x86_64, then run inside QEMU.",
        .headers_zh = "典型方向：backend.x86_64-asm 搭配 target.freestanding-x86_64 或 target.baremetal-x86_64，然后放进 QEMU 里跑。",
        .goal_en = "Understand the workflow split between hosted programs and bootable or emulated artifacts.",
        .goal_zh = "理解 hosted 程序和 boot / 模拟产物之间的工作流分叉。",
        .example_code = "unsafe.enable\nbackend.x86_64-asm\ntarget.baremetal-x86_64\n\nmain:\n  print \"boot path\"\n  ret 0\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "kernel.process",
        .slug = "kernel.process",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Kernel Process Concepts",
        .title_zh = "内核进程",
        .summary_en = "A conceptual ultra-hard card about process, scheduling, and kernel-near experimentation.",
        .summary_zh = "一个超难概念卡片，讲进程、调度，以及更靠近内核的实验方向。",
        .notes_en = "This node is not pretending that Machine 2.0 instantly gives you a full kernel-process framework. Instead, it introduces the vocabulary and the kinds of lower-level primitives that eventually matter: memory layout, syscall boundaries, scheduler ideas, and boot/runtime targets.",
        .notes_zh = "这个节点不会假装 Machine 2.0 现在就直接给你一整套“内核进程框架”。它更像概念入口：先认识进程、调度、syscall 边界、内存布局，以及 boot/runtime 目标这些真正会影响内核实验的底层因素。",
        .headers_en = "Read after syscall, freestanding, baremetal, and VGA cards.",
        .headers_zh = "建议在看完 syscall、freestanding、baremetal、VGA 这些节点之后再读。",
        .goal_en = "Use this card as a conceptual map before you build lower-level experiments outside the hosted lesson flow.",
        .goal_zh = "把这张卡当成概念地图，之后再去做 hosted 流程之外的更底层实验。",
        .example_code = "-- concept card\n-- scheduler\n-- process state\n-- kernel entry path\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "algo.logic",
        .slug = "algo.logic",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "High-Logic Algorithm",
        .title_zh = "高逻辑算法",
        .summary_en = "Write a compact but structured logic-heavy program.",
        .summary_zh = "写一个逻辑比较密集、但仍然结构清晰的程序。",
        .notes_en = "This advanced node is about shaping logic cleanly under moderate complexity: helper functions, branches, loops, and a small amount of state.",
        .notes_zh = "这个进阶节点重点是：在逻辑开始变复杂时，仍然把函数、分支、循环和少量状态组织清楚。",
        .headers_en = "No mandatory directive set, but bin.runtime is fine for normal Linux execution.",
        .headers_zh = "没有强制指令组合；如果你要走普通 Linux 路线，bin.runtime 就够了。",
        .goal_en = "Write a logic-heavy program and output exactly:\n1\n4\n9\n16",
        .goal_zh = "写一个逻辑较重的程序，并准确输出：\n1\n4\n9\n16",
        .example_code = "func sq(x: i64) -> i64:\n  ret x * x\n\nmain:\n  var i: i64 = 1\n  while i <= 4:\n    print sq(i)\n    -- still finish the loop and ret 0\n",
        .editor_default = "",
        .expected_output = "1\n4\n9\n16",
        .required_tokens = {"func ", "while ", "*", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "algo.fast_inv_sqrt",
        .slug = "algo.fast_inv_sqrt",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Fast Inverse Square Root",
        .title_zh = "快速平方根算法",
        .summary_en = "A challenge card for the classic fast inverse square root idea.",
        .summary_zh = "一个围绕经典快速平方根思想的进阶挑战卡片。",
        .notes_en = "This node is provided as an advanced study card in the current build. It discusses why fast inverse square root is famous, what bit-level assumptions it leans on, and why Machine low-level features make it an interesting later experiment.",
        .notes_zh = "当前版本里，这个节点先作为进阶研究卡片存在。它会讲为什么快速平方根算法这么有名、它依赖哪些位级假设，以及为什么 Machine 的底层能力让它适合作为后续实验。",
        .headers_en = "Useful background: f64/f32 thinking, ptr conversions, raw memory, and performance measurement.",
        .headers_zh = "建议先熟悉：浮点思维、指针转换、原始内存、性能测量。",
        .goal_en = "Treat this card as a preparation node before you implement or optimize the classic trick yourself.",
        .goal_zh = "先把这张卡当成准备节点，之后再自己实现或优化那套经典技巧。",
        .example_code = "-- advanced study card\n-- inverse sqrt\n-- bit reinterpretation\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "algo.newton",
        .slug = "algo.newton",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Newton Fast Iteration",
        .title_zh = "牛顿快速迭代法",
        .summary_en = "Use iteration to converge on a better numeric answer.",
        .summary_zh = "用迭代逐步逼近更好的数值结果。",
        .notes_en = "This advanced node uses a small Newton-style loop. The current teaching target stays simple enough that you can focus on iterative structure rather than numerical edge cases.",
        .notes_zh = "这个进阶节点会用一个小型牛顿式循环。当前教学目标故意保持简单，让你先把注意力放在“迭代结构”上，而不是数值边界问题。",
        .headers_en = "No strict directive requirement. f64 is recommended.",
        .headers_zh = "没有强制指令要求，但建议使用 f64。",
        .goal_en = "Write an iterative approximation program and make the output include 1.4.",
        .goal_zh = "写一个迭代逼近程序，并让输出里包含 1.4。",
        .example_code = "main:\n  var x: f64 = 2.0\n  var guess: f64 = 1.0\n  -- still iterate toward sqrt(2) and print the final approximation\n",
        .editor_default = "",
        .expected_output = "1.4",
        .required_tokens = {"f64", "while ", "print", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "algo.high_precision",
        .slug = "algo.high_precision",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Highest Precision",
        .title_zh = "最高精度算法",
        .summary_en = "A study card about precision, hp values, and algorithmic trade-offs.",
        .summary_zh = "一个讲精度、hp 数值和算法权衡的进阶研究卡片。",
        .notes_en = "The current build includes hp as a type family, but this node is presented as a study card first because the best teaching examples depend on the exact runtime and formatting behavior you want to emphasize.",
        .notes_zh = "当前版本里虽然有 hp 这个类型族，但这张卡先以研究说明为主，因为真正最好的教学示例会依赖你想强调的运行时与格式化行为。",
        .headers_en = "Read after f64 and iteration lessons.",
        .headers_zh = "建议在 f64 与迭代类课程之后阅读。",
        .goal_en = "Use this node to think about when high precision is worth the extra complexity.",
        .goal_zh = "把这张卡当成思考题：什么时候“更高精度”值得你付出额外复杂度。",
        .example_code = "-- study card\n-- hp precision\n-- algorithm trade-offs\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "sort.quicksort",
        .slug = "sort.quicksort",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Quick Sort",
        .title_zh = "快速排序算法",
        .summary_en = "Sort a small data set and print it in ascending order.",
        .summary_zh = "对一组小数据做排序，并按升序输出。",
        .notes_en = "This is an advanced algorithm node. You can use recursion or an iterative approach if the current compiler/runtime path suits it. The teaching goal is clear ordering logic and visible output.",
        .notes_zh = "这是一个进阶算法节点。你可以用递归，也可以用更适合当前编译路径的迭代变体。教学重点是排序逻辑清楚，并且输出可见。",
        .headers_en = "No mandatory directive requirement.",
        .headers_zh = "没有强制指令要求。",
        .goal_en = "Sort the data and output exactly:\n1\n2\n3\n4\n5",
        .goal_zh = "把数据排好序，并准确输出：\n1\n2\n3\n4\n5",
        .example_code = "-- choose your own quicksort style\nmain:\n  -- prepare data\n  -- sort it\n  -- print it in ascending order\n",
        .editor_default = "",
        .expected_output = "1\n2\n3\n4\n5",
        .required_tokens = {"print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "asm.inline",
        .slug = "asm.inline",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Inline ASM",
        .title_zh = "内联汇编",
        .summary_en = "Practice a harder node that introduces inline assembly helpers and register-oriented thinking.",
        .summary_zh = "进入更难一些的节点：接触内联汇编辅助函数与寄存器导向思维。",
        .notes_en = "This node is for learners who already understand basic control flow and pointers. The focus is not writing a huge assembly program, but learning how Machine can expose lower-level building blocks for small experiments.",
        .notes_zh = "这一关面向已经熟悉基础控制流和指针的学习者。重点不是手写一大段汇编，而是理解 Machine 怎样把更底层的构件暴露出来，让你做小型实验。",
        .headers_en = "Likely directives: unsafe.enable and whichever backend/runtime model your experiment really needs.",
        .headers_zh = "常见会用到：unsafe.enable，以及你的实验真正需要的 backend/runtime 指令。",
        .goal_en = "Build a small inline-ASM-flavored experiment and print exactly:\n17\n34",
        .goal_zh = "完成一个带有内联汇编风格的小实验，并准确输出：\n17\n34",
        .example_code = "unsafe.enable\n\nmain:\n  -- prepare one small asm-style experiment\n  -- keep the final output visible\n  ret 0\n",
        .editor_default = "",
        .expected_output = "17\n34",
        .required_tokens = {"unsafe.enable", "main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "volatile.mmio",
        .slug = "volatile.mmio",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Volatile Memory",
        .title_zh = "易失性内存实验",
        .summary_en = "A harder node about volatile loads and stores in a low-level memory setting.",
        .summary_zh = "更难一点的节点：在偏底层的内存场景里练 volatile 读写。",
        .notes_en = "Volatile access matters when the memory location can change outside ordinary program flow, for example MMIO-like experiments. The lesson goal is to write a compact, explicit program and preserve the visible output.",
        .notes_zh = "当某个内存位置可能在普通程序流程之外发生变化时，volatile 访问就很重要，例如 MMIO 风格实验。教学目标是写出紧凑、显式的程序，并保留可见输出。",
        .headers_en = "Usually needs unsafe.enable. Add hosted or freestanding directives according to your experiment.",
        .headers_zh = "通常需要 unsafe.enable。至于 hosted 或 freestanding，请按实验需求选择。",
        .goal_en = "Use volatile-style memory access and output exactly:\n1\n2\n3",
        .goal_zh = "使用 volatile 风格的内存访问，并准确输出：\n1\n2\n3",
        .example_code = "unsafe.enable\n\nmain:\n  -- set up one small volatile memory exercise\n  -- print the visible values\n  ret 0\n",
        .editor_default = "",
        .expected_output = "1\n2\n3",
        .required_tokens = {"unsafe.enable", "main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "apic.timer",
        .slug = "apic.timer",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "APIC Timer",
        .title_zh = "APIC 定时器",
        .summary_en = "An extreme node for learners stepping into APIC timer setup and observable low-level state.",
        .summary_zh = "超难节点：进入 APIC 定时器设置与可观察的底层状态。",
        .notes_en = "Treat this as a lab card. The point is to connect Machine's low-level helpers with hardware-oriented reasoning. A good answer is small, explicit, and accompanied by visible output that proves the path ran.",
        .notes_zh = "把它当成实验卡片来看待。重点是把 Machine 的底层辅助函数和面向硬件的思考连起来。好的答案应该足够小、足够明确，并且有可见输出证明这条路径确实跑到了。",
        .headers_en = "Common setup: unsafe.enable plus freestanding or baremetal target lines depending on your APIC experiment.",
        .headers_zh = "常见设置：unsafe.enable，再配合 freestanding 或 baremetal 目标行，具体取决于你的 APIC 实验。",
        .goal_en = "Make a compact APIC timer experiment and print exactly:\nAPIC\nTIMER\nREADY",
        .goal_zh = "完成一个紧凑的 APIC 定时器实验，并准确输出：\nAPIC\nTIMER\nREADY",
        .example_code = "unsafe.enable\n\nmain:\n  -- connect one APIC timer path\n  -- keep the final visible output simple\n  ret 0\n",
        .editor_default = "",
        .expected_output = "APIC\nTIMER\nREADY",
        .required_tokens = {"unsafe.enable", "main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "page.map2m",
        .slug = "page.map2m",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "2M Identity Mapping",
        .title_zh = "2M 页恒等映射",
        .summary_en = "An extreme lesson around page_identity_map_2m and page-table style thinking.",
        .summary_zh = "围绕 page_identity_map_2m 与页表式思维的超难课程。",
        .notes_en = "The lesson is intentionally hard. You do not need a gigantic kernel here. The goal is to understand what a 2M identity-mapping helper means, set up a small experiment, and keep the output visible.",
        .notes_zh = "这一关是故意偏难的。这里不要求你写一个巨大的内核，而是要理解 2M 恒等映射辅助函数意味着什么，搭一个小实验，并保留可见输出。",
        .headers_en = "Likely directives: unsafe.enable plus freestanding or baremetal target lines.",
        .headers_zh = "常见指令：unsafe.enable，再加上 freestanding 或 baremetal 目标行。",
        .goal_en = "Build a page-mapping experiment and print exactly:\nMAP\n2M\nREADY",
        .goal_zh = "完成一个页映射实验，并准确输出：\nMAP\n2M\nREADY",
        .example_code = "unsafe.enable\n\nmain:\n  -- prepare one small 2M identity mapping test\n  -- keep the final output easy to verify\n  ret 0\n",
        .editor_default = "",
        .expected_output = "MAP\n2M\nREADY",
        .required_tokens = {"unsafe.enable", "main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "boot.chain",
        .slug = "boot.chain",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Boot Chain",
        .title_zh = "引导链实验",
        .summary_en = "A super-hard lab card about the idea of boot flow, handoff, and visible checkpoints.",
        .summary_zh = "一个关于引导流程、阶段交接与可见检查点的超难实验卡。",
        .notes_en = "Keep this node practical: define a small boot-oriented scenario, mark checkpoints clearly, and make the output show the route. The emphasis is reasoning and structure, not just length.",
        .notes_zh = "这一关尽量保持实用：定义一个小型面向引导的场景，清楚标出检查点，并让输出能够说明路径。重点是思路和结构，而不只是代码长度。",
        .headers_en = "Common setup may involve unsafe.enable and a freestanding or baremetal target. Use what your scenario truly needs.",
        .headers_zh = "常见会涉及 unsafe.enable 与 freestanding / baremetal 目标。按你的场景真实需求来写。",
        .goal_en = "Create a visible boot-chain experiment and print exactly:\nBOOT\nCHAIN\nOK",
        .goal_zh = "写一个可见的引导链实验，并准确输出：\nBOOT\nCHAIN\nOK",
        .example_code = "unsafe.enable\n\nmain:\n  -- model a tiny boot-chain path\n  -- print visible checkpoints\n  ret 0\n",
        .editor_default = "",
        .expected_output = "BOOT\nCHAIN\nOK",
        .required_tokens = {"unsafe.enable", "main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "algo.matrix",
        .slug = "algo.matrix",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Matrix Multiply",
        .title_zh = "矩阵乘法优化",
        .summary_en = "An advanced challenge about data layout, loops, and visible matrix results.",
        .summary_zh = "围绕数据布局、循环与可见矩阵结果的进阶挑战。",
        .notes_en = "This challenge is great for comparing straightforward code with more thoughtful data access order. Keep the workload understandable and print enough output to verify the algorithm.",
        .notes_zh = "这类挑战很适合比较“直接写法”和“更讲究访问顺序的写法”。请让工作负载足够清楚，并打印足够的结果来验证算法。",
        .headers_en = "No mandatory directive requirement unless your implementation truly needs one.",
        .headers_zh = "除非你的实现确实需要，否则没有强制指令要求。",
        .goal_en = "Multiply a small matrix setup and print exactly:\n19\n22\n43\n50",
        .goal_zh = "完成一个小型矩阵乘法，并准确输出：\n19\n22\n43\n50",
        .example_code = "main:\n  -- prepare two small matrices\n  -- multiply them\n  -- print the result in row order\n  ret 0\n",
        .editor_default = "",
        .expected_output = "19\n22\n43\n50",
        .required_tokens = {"main:", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "bench.compile",
        .slug = "bench.compile",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_BENCH_COMPILE,
        .compile_target_ms = 2500,
        .run_target_ms = 0,
        .title_en = "Compile Speed",
        .title_zh = "编译速率",
        .summary_en = "A benchmark node that checks whether your lesson program compiles under the current threshold.",
        .summary_zh = "一个会检查“当前课程程序编译时间是否达标”的性能节点。",
        .notes_en = "This node measures the wall-clock compile time of your current lesson source. The threshold in this build is intentionally forgiving so you can start comparing versions of your own code and gradually push lower.",
        .notes_zh = "这个节点会测量你当前课程源码的编译耗时。当前构建里的门槛是故意放宽过的，目的是让你先开始比较不同版本代码，再慢慢往更低耗时推进。",
        .headers_en = "Use whatever directive set your benchmark program actually needs.",
        .headers_zh = "你的基准程序需要什么指令，就写什么。",
        .goal_en = "Make a non-trivial program compile within the current threshold. This build starts with 2500 ms.",
        .goal_zh = "写一个非平凡程序，并让它在当前门槛内完成编译。本版本起始门槛是 2500 ms。",
        .example_code = "struct Node:\n  value: i64\n\nfunc helper(x: i64) -> i64:\n  ret x + 1\n\nmain:\n  -- make this program larger and more interesting\n  print \"compile benchmark ready\"\n  ret 0\n",
        .editor_default = "",
        .expected_output = "compile benchmark ready",
        .required_tokens = {"struct ", "func ", "main:", "print", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "bench.run",
        .slug = "bench.run",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_BENCH_RUN,
        .compile_target_ms = 0,
        .run_target_ms = 1200,
        .title_en = "Run Speed",
        .title_zh = "运行速率",
        .summary_en = "A benchmark node that checks whether your lesson program runs under the current threshold.",
        .summary_zh = "一个会检查“当前课程程序运行时间是否达标”的性能节点。",
        .notes_en = "This node measures execution time after a successful compile. Start with a clear workload so the run time reflects your algorithmic choices rather than random noise.",
        .notes_zh = "这个节点会在成功编译后测量执行时间。建议你先准备一个比较明确的工作负载，这样运行时间才更能体现算法选择，而不是随机噪声。",
        .headers_en = "Use the directive set that matches your benchmark program.",
        .headers_zh = "按你的基准程序需要来选择指令。",
        .goal_en = "Make the lesson program run within the current threshold. This build starts with 1200 ms.",
        .goal_zh = "让课程程序在当前门槛内完成运行。本版本起始门槛是 1200 ms。",
        .example_code = "main:\n  var i: i64 = 0\n  var acc: i64 = 0\n  while i < 100000:\n    acc = acc + i\n    i = i + 1\n  print \"run benchmark ready\"\n  ret 0\n",
        .editor_default = "",
        .expected_output = "run benchmark ready",
        .required_tokens = {"while ", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "allocator.bump",
        .slug = "allocator.bump",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_HARD,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Bump Allocator",
        .title_zh = "线性分配器",
        .summary_en = "Build a tiny bump allocator idea on top of raw memory.",
        .summary_zh = "在原始内存之上理解一个极简 bump allocator 的思路。",
        .notes_en = "This lesson is harder because it mixes pointer arithmetic, raw memory layout, and allocator state. Keep the state tiny and verify each step with prints.",
        .notes_zh = "这一关更难，因为它把指针运算、原始内存布局和分配器状态混到了一起。建议把状态压到最小，并且每一步都用 print 验证。",
        .headers_en = "Usually bin.runtime + unsafe.enable, and raw pointer arithmetic often belongs inside unsafe: blocks.",
        .headers_zh = "通常会用到 bin.runtime + unsafe.enable，而且原始指针运算往往需要放进 unsafe: 块。",
        .goal_en = "Print exactly:\n16\n24\n32",
        .goal_zh = "准确输出：\n16\n24\n32",
        .example_code = "bin.runtime\nunsafe.enable\n\nmain:\n  -- manage a moving allocation cursor here\n  ret 0\n",
        .editor_default = "",
        .expected_output = "16\n24\n32",
        .required_tokens = {"unsafe.enable", "unsafe:", "ptr_offset", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "syscall.table",
        .slug = "syscall.table",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Syscall Table Reading",
        .title_zh = "syscall 表阅读",
        .summary_en = "Read how syscall numbers, arguments, and return values line up before writing very low-level code.",
        .summary_zh = "在真正手写更底层代码之前，先理解 syscall 编号、参数和返回值是怎样对齐的。",
        .notes_en = "This node is extreme because it sits close to ABI details. The main purpose is to understand what syscall0..syscall6 are trying to expose.",
        .notes_zh = "这一关属于超难，因为它已经非常靠近 ABI 细节。主要目的是让你理解 syscall0..syscall6 这一组到底在暴露什么。",
        .headers_en = "Often bin.runtime for Linux experiments, or target-specific directives for lower-level environments.",
        .headers_zh = "Linux 实验常见 bin.runtime，更低层环境则会切换到对应 target 指令。",
        .goal_en = "Understand the mapping first. This page focuses on concepts before practice.",
        .goal_zh = "先理解映射关系。本页以概念讲解优先。",
        .example_code = "-- syscall3(number, a, b, c)\n-- return value comes back as i64\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "kernel.scheduler",
        .slug = "kernel.scheduler",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_EXTREME,
        .mode = LESSON_MODE_INFO,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Kernel Scheduling Notes",
        .title_zh = "内核调度笔记",
        .summary_en = "A concept page for process state, run queues, and the kind of control logic you would need in a tiny kernel.",
        .summary_zh = "理解进程状态、运行队列，以及一个微型内核调度器会需要什么控制逻辑。",
        .notes_en = "This page is intentionally conceptual. You do not start with a full kernel scheduler implementation; you first learn what a scheduler must remember and decide.",
        .notes_zh = "这个页面故意以概念为主。你不会一上来就写完整内核调度器，而是先理解一个调度器必须记住什么、决定什么。",
        .headers_en = "Target-specific headers depend on whether you are still simulating on Linux or moving into baremetal experiments.",
        .headers_zh = "具体指令要看你是还在 Linux 模拟，还是已经进入 baremetal 实验。",
        .goal_en = "Understand the moving parts before entering kernel-level challenge nodes.",
        .goal_zh = "在真正进入内核级挑战前，先把关键部件想清楚。",
        .example_code = "struct Task:\n  id: i64\n  state: i64\n  ticks: i64\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "algo.graph_search",
        .slug = "algo.graph_search",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_OUTPUT,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Graph Search Challenge",
        .title_zh = "图搜索挑战",
        .summary_en = "An advanced challenge focused on control flow, containers, and careful state updates.",
        .summary_zh = "一个强调控制流、容器与状态更新的进阶挑战。",
        .notes_en = "You can solve this in several ways: direct arrays, lists, or even a simple manual queue. The point is to organize state clearly.",
        .notes_zh = "这关可以有多种解法：直接用数组、列表，或者手写一个简单队列。关键在于把状态组织清楚。",
        .headers_en = "Choose only the directives your graph-search program truly needs.",
        .headers_zh = "按你的图搜索程序真实需要来选择指令。",
        .goal_en = "Print exactly:\nreachable\n3",
        .goal_zh = "准确输出：\nreachable\n3",
        .example_code = "main:\n  -- represent a tiny graph and search from a start node\n  ret 0\n",
        .editor_default = "",
        .expected_output = "reachable\n3",
        .required_tokens = {"while ", "if ", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "bench.program",
        .slug = "bench.program",
        .challenge = TRUE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_BENCH_PROGRAM,
        .compile_target_ms = 2500,
        .run_target_ms = 1200,
        .title_en = "Program Performance",
        .title_zh = "程序性能",
        .summary_en = "A combined benchmark node that checks both compile time and run time.",
        .summary_zh = "一个同时检查编译时间和运行时间的综合性能节点。",
        .notes_en = "This node combines both parts: compile speed and run speed. It is a good place to compare different program organizations and see whether a change helped one side while hurting the other.",
        .notes_zh = "这个节点把两部分合并起来：编译速度和运行速度。它适合拿来比较不同程序组织方式，看看某个改动是不是帮到了其中一边，却拖慢了另一边。",
        .headers_en = "Use the directive set your combined benchmark program truly needs.",
        .headers_zh = "按你的综合基准程序实际需要来选择指令。",
        .goal_en = "Meet both thresholds in one run. Current build: compile <= 2500 ms and run <= 1200 ms.",
        .goal_zh = "在一次运行里同时满足两条门槛。当前版本：编译 <= 2500 ms，运行 <= 1200 ms。",
        .example_code = "struct Box:\n  value: i64\n\nfunc work(x: i64) -> i64:\n  ret x * x\n\nmain:\n  -- combine code size and runtime work\n  print \"program performance ready\"\n  ret 0\n",
        .editor_default = "",
        .expected_output = "program performance ready",
        .required_tokens = {"struct ", "func ", "print", "ret 0", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    },
    {
        .id = "quiz.choice",
        .slug = "quiz.choice",
        .challenge = FALSE,
        .difficulty = LESSON_DIFFICULTY_ADVANCED,
        .mode = LESSON_MODE_QUIZ,
        .compile_target_ms = 0,
        .run_target_ms = 0,
        .title_en = "Multiple Choice",
        .title_zh = "选择题",
        .summary_en = "Answer 50 theory questions about Machine 2.0 and get a score out of 100.",
        .summary_zh = "完成 50 道关于 Machine 2.0 的理论选择题，并得到满分 100 的分数。",
        .notes_en = "Each question is worth 2 points. Finish all 50 first, then submit once to see your score and the explanations for wrong answers.",
        .notes_zh = "每题 2 分。先把 50 题全部做完，再统一提交并查看分数与错题解析。",
        .headers_en = "No code headers are needed here because this is a theory-only node.",
        .headers_zh = "这里是纯理论关卡，所以不需要任何代码预编译头。",
        .goal_en = "Answer every question, then submit and read the explanations carefully.",
        .goal_zh = "把全部题目做完后提交，并认真看解析。",
        .example_code = "-- Theory-only node\n-- The editor is disabled here\n",
        .editor_default = "",
        .expected_output = "",
        .required_tokens = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    }

};

const LessonSpec *app_lessons_all(gsize *count_out) {
  if (count_out) {
    *count_out = G_N_ELEMENTS(LESSONS);
  }
  return LESSONS;
}

const LessonSpec *app_lesson_find(const gchar *lesson_id) {
  for (gsize i = 0; i < G_N_ELEMENTS(LESSONS); ++i) {
    if (g_strcmp0(LESSONS[i].id, lesson_id) == 0) {
      return &LESSONS[i];
    }
  }
  return &LESSONS[0];
}

static const gchar *pick_lang(const gchar *language, const gchar *en, const gchar *zh) {
  return g_strcmp0(app_lang_normalize(language), "zh-CN") == 0 ? zh : en;
}

const gchar *app_lesson_title(const LessonSpec *lesson, const gchar *language) {
  return lesson ? pick_lang(language, lesson->title_en, lesson->title_zh) : "";
}

const gchar *app_lesson_summary(const LessonSpec *lesson, const gchar *language) {
  return lesson ? pick_lang(language, lesson->summary_en, lesson->summary_zh) : "";
}

const gchar *app_lesson_notes(const LessonSpec *lesson, const gchar *language) {
  return lesson ? pick_lang(language, lesson->notes_en, lesson->notes_zh) : "";
}

const gchar *app_lesson_headers(const LessonSpec *lesson, const gchar *language) {
  return lesson ? pick_lang(language, lesson->headers_en, lesson->headers_zh) : "";
}

const gchar *app_lesson_goal(const LessonSpec *lesson, const gchar *language) {
  return lesson ? pick_lang(language, lesson->goal_en, lesson->goal_zh) : "";
}

const gchar *app_lesson_difficulty_text(LessonDifficulty difficulty, const gchar *language) {
  switch (difficulty) {
    case LESSON_DIFFICULTY_NORMAL:
      return app_i18n_get(language, "badge.normal");
    case LESSON_DIFFICULTY_HARD:
      return app_i18n_get(language, "badge.hard");
    case LESSON_DIFFICULTY_EXTREME:
      return app_i18n_get(language, "badge.extreme");
    case LESSON_DIFFICULTY_ADVANCED:
      return app_i18n_get(language, "badge.advanced");
    case LESSON_DIFFICULTY_NONE:
    default:
      return NULL;
  }
}

const gchar *app_lesson_difficulty_css_class(LessonDifficulty difficulty) {
  switch (difficulty) {
    case LESSON_DIFFICULTY_NORMAL:
      return "lesson-badge-normal";
    case LESSON_DIFFICULTY_HARD:
      return "lesson-badge-hard";
    case LESSON_DIFFICULTY_EXTREME:
      return "lesson-badge-extreme";
    case LESSON_DIFFICULTY_ADVANCED:
      return "lesson-badge-advanced";
    case LESSON_DIFFICULTY_NONE:
    default:
      return NULL;
  }
}
