#include "quiz_data.h"

static const QuizQuestion QUESTIONS[] = {
  {
    .prompt_en = "(1) Which top-level form starts the normal entry block?",
    .prompt_zh = "（1）哪个顶层形式表示普通程序入口块？",
    .choices_en = {"A. main:", "B. entry:", "C. start:"},
    .choices_zh = {"A. main:", "B. entry:", "C. start:"},
    .correct_index = 0,
    .explain_en = "main: is the standard entry block in current Machine 2.0. The other two names are not valid top-level entry forms.",
    .explain_zh = "当前 Machine 2.0 的标准入口块是 main:。另外两个名字都不是合法顶层入口形式。",
  },
  {
    .prompt_en = "(2) Which directive is commonly used for hosted Linux runtime lessons?",
    .prompt_zh = "（2）哪个指令常用于 hosted Linux 运行时教学关卡？",
    .choices_en = {"A. bin.runtime", "B. target.baremetal-x86_64", "C. module.runtime"},
    .choices_zh = {"A. bin.runtime", "B. target.baremetal-x86_64", "C. module.runtime"},
    .correct_index = 0,
    .explain_en = "bin.runtime selects the hosted runtime path. baremetal targets and made-up module.runtime mean something else or are invalid here.",
    .explain_zh = "bin.runtime 用来选择 hosted 运行时路径。baremetal 目标和虚构的 module.runtime 在这里都不对。",
  },
  {
    .prompt_en = "(3) In Machine, which statement prints a value to standard output?",
    .prompt_zh = "（3）在 Machine 里，哪个语句会把值打印到标准输出？",
    .choices_en = {"A. echo", "B. print", "C. out"},
    .choices_zh = {"A. echo", "B. print", "C. out"},
    .correct_index = 1,
    .explain_en = "print is the output statement used in the current language. echo and out are not the standard statement here.",
    .explain_zh = "当前语言里负责输出的是 print。echo 和 out 不是这里的标准语句。",
  },
  {
    .prompt_en = "(4) Which keyword returns from a function or main block?",
    .prompt_zh = "（4）哪个关键字会从函数或 main 块里返回？",
    .choices_en = {"A. stop", "B. break", "C. ret"},
    .choices_zh = {"A. stop", "B. break", "C. ret"},
    .correct_index = 2,
    .explain_en = "ret returns from the current function-like block. break only leaves loops or switch-like flows when supported.",
    .explain_zh = "ret 用来从当前函数式代码块返回。break 只用于离开循环或类似结构。",
  },
  {
    .prompt_en = "(5) Which type name represents a 64-bit integer?",
    .prompt_zh = "（5）哪个类型名表示 64 位整数？",
    .choices_en = {"A. i64", "B. int64_t", "C. s64"},
    .choices_zh = {"A. i64", "B. int64_t", "C. s64"},
    .correct_index = 0,
    .explain_en = "The built-in integer type name used in Machine is i64.",
    .explain_zh = "Machine 当前使用的内建整数类型名是 i64。",
  },
  {
    .prompt_en = "(6) Which type name represents a floating-point number in current Machine 2.0?",
    .prompt_zh = "（6）当前 Machine 2.0 中哪个类型名表示浮点数？",
    .choices_en = {"A. float", "B. f64", "C. fp64"},
    .choices_zh = {"A. float", "B. f64", "C. fp64"},
    .correct_index = 1,
    .explain_en = "f64 is the floating-point type name used here.",
    .explain_zh = "这里使用的浮点类型名是 f64。",
  },
  {
    .prompt_en = "(7) Which type name is used for boolean values?",
    .prompt_zh = "（7）哪个类型名用于布尔值？",
    .choices_en = {"A. boolean", "B. bool", "C. flag"},
    .choices_zh = {"A. boolean", "B. bool", "C. flag"},
    .correct_index = 1,
    .explain_en = "The boolean type is bool in current Machine.",
    .explain_zh = "当前 Machine 中布尔类型写作 bool。",
  },
  {
    .prompt_en = "(8) Which literal pair represents the two boolean values?",
    .prompt_zh = "（8）哪一对字面量表示布尔真与假？",
    .choices_en = {"A. yes / no", "B. on / off", "C. true / false"},
    .choices_zh = {"A. yes / no", "B. on / off", "C. true / false"},
    .correct_index = 2,
    .explain_en = "Machine uses true and false as boolean literals.",
    .explain_zh = "Machine 使用 true 和 false 作为布尔字面量。",
  },
  {
    .prompt_en = "(9) Which type is used for pointer values?",
    .prompt_zh = "（9）哪个类型用于指针值？",
    .choices_en = {"A. ptr", "B. ref", "C. addr64"},
    .choices_zh = {"A. ptr", "B. ref", "C. addr64"},
    .correct_index = 0,
    .explain_en = "ptr is the pointer type name in current Machine 2.0.",
    .explain_zh = "当前 Machine 2.0 中指针类型名是 ptr。",
  },
  {
    .prompt_en = "(10) Which statement creates a mutable variable?",
    .prompt_zh = "（10）哪个语句用于创建可变变量？",
    .choices_en = {"A. const", "B. var", "C. let"},
    .choices_zh = {"A. const", "B. var", "C. let"},
    .correct_index = 1,
    .explain_en = "var declares a mutable variable. const declares a constant.",
    .explain_zh = "var 声明可变变量，const 声明常量。",
  },
  {
    .prompt_en = "(11) Which declaration starts a user-defined structure?",
    .prompt_zh = "（11）哪个声明用于定义用户结构体？",
    .choices_en = {"A. class", "B. object", "C. struct"},
    .choices_zh = {"A. class", "B. object", "C. struct"},
    .correct_index = 2,
    .explain_en = "struct starts a structure definition in Machine.",
    .explain_zh = "Machine 中用 struct 开始一个结构体定义。",
  },
  {
    .prompt_en = "(12) Which declaration groups related functions under one namespace-like name?",
    .prompt_zh = "（12）哪个声明会把相关函数归到一个类似命名空间的名字下面？",
    .choices_en = {"A. package", "B. module", "C. group"},
    .choices_zh = {"A. package", "B. module", "C. group"},
    .correct_index = 1,
    .explain_en = "module is the language feature used to group related functions.",
    .explain_zh = "module 是这里用于分组相关函数的语言特性。",
  },
  {
    .prompt_en = "(13) Which code is correct for equality comparison?",
    .prompt_zh = "（13）下面哪个写法表示“相等比较”？",
    .choices_en = {"A. a = b", "B. a == b", "C. a := b"},
    .choices_zh = {"A. a = b", "B. a == b", "C. a := b"},
    .correct_index = 1,
    .explain_en = "== performs comparison. = is assignment.",
    .explain_zh = "== 才是比较，相反 = 是赋值。",
  },
  {
    .prompt_en = "(14) Which code is correct for not-equal comparison?",
    .prompt_zh = "（14）下面哪个写法表示“不相等比较”？",
    .choices_en = {"A. a != b", "B. a <> b", "C. a ~= b"},
    .choices_zh = {"A. a != b", "B. a <> b", "C. a ~= b"},
    .correct_index = 0,
    .explain_en = "!= is the supported not-equal operator in current Machine lessons.",
    .explain_zh = "当前 Machine 教学中支持的不等于运算符是 !=。",
  },
  {
    .prompt_en = "(15) Which block form is indentation-sensitive?",
    .prompt_zh = "（15）哪个结构是缩进敏感的？",
    .choices_en = {"A. if / elif / else", "B. only comments", "C. only struct fields"},
    .choices_zh = {"A. if / elif / else", "B. 只有注释", "C. 只有结构体字段"},
    .correct_index = 0,
    .explain_en = "if / elif / else use indentation-sensitive blocks, and so do other block forms such as main:, func, and while.",
    .explain_zh = "if / elif / else 使用缩进敏感块，main:、func、while 等也一样。",
  },
  {
    .prompt_en = "(16) Which keyword repeats a block while a condition stays true?",
    .prompt_zh = "（16）哪个关键字会在条件为真时重复执行代码块？",
    .choices_en = {"A. repeat", "B. while", "C. loop"},
    .choices_zh = {"A. repeat", "B. while", "C. loop"},
    .correct_index = 1,
    .explain_en = "while is the loop keyword used in current Machine.",
    .explain_zh = "当前 Machine 中用于循环的是 while。",
  },
  {
    .prompt_en = "(17) In 'func add(a: i64, b: i64) -> i64:', what does '-> i64' mean?",
    .prompt_zh = "（17）在 'func add(a: i64, b: i64) -> i64:' 中，'-> i64' 表示什么？",
    .choices_en = {"A. the return type is i64", "B. add can only be called twice", "C. a and b are arrays"},
    .choices_zh = {"A. 返回类型是 i64", "B. add 只能被调用两次", "C. a 和 b 是数组"},
    .correct_index = 0,
    .explain_en = "The arrow introduces the function return type.",
    .explain_zh = "箭头后面写的是函数返回类型。",
  },
  {
    .prompt_en = "(18) Which line correctly constructs a value from a struct named Pair?",
    .prompt_zh = "（18）对于名为 Pair 的结构体，哪一行能正确构造其值？",
    .choices_en = {"A. var p = Pair()", "B. var p = new Pair", "C. var p = Pair{}"},
    .choices_zh = {"A. var p = Pair()", "B. var p = new Pair", "C. var p = Pair{}"},
    .correct_index = 0,
    .explain_en = "The current lessons use Pair() construction syntax.",
    .explain_zh = "当前课程里使用的是 Pair() 这种构造写法。",
  },
  {
    .prompt_en = "(19) Which expression reads a struct field named title from card?",
    .prompt_zh = "（19）要从 card 里读取名为 title 的字段，哪个表达式正确？",
    .choices_en = {"A. card->title", "B. card.title", "C. title.card"},
    .choices_zh = {"A. card->title", "B. card.title", "C. title.card"},
    .correct_index = 1,
    .explain_en = "Field access uses dot syntax in current Machine lessons.",
    .explain_zh = "当前 Machine 课程中的字段访问使用点号语法。",
  },
  {
    .prompt_en = "(20) What does this output?\nmain:\n  print 2 + 3 * 4\n  ret 0",
    .prompt_zh = "（20）下面这段代码会输出什么？\nmain:\n  print 2 + 3 * 4\n  ret 0",
    .choices_en = {"A. 20", "B. 14", "C. 24"},
    .choices_zh = {"A. 20", "B. 14", "C. 24"},
    .correct_index = 1,
    .explain_en = "Multiplication has to be evaluated before addition here, so the expression becomes 2 + 12.",
    .explain_zh = "这里要先算乘法再算加法，所以表达式会变成 2 + 12。",
  },
  {
    .prompt_en = "(21) What does this output?\nmain:\n  print 5 == 4\n  ret 0",
    .prompt_zh = "（21）下面这段代码会输出什么？\nmain:\n  print 5 == 4\n  ret 0",
    .choices_en = {"A. 0", "B. 1", "C. false"},
    .choices_zh = {"A. 0", "B. 1", "C. false"},
    .correct_index = 0,
    .explain_en = "In the current compiler, printing a false boolean comparison yields 0.",
    .explain_zh = "在当前编译器里，打印布尔假比较通常得到 0。",
  },
  {
    .prompt_en = "(22) Which statement best describes goto in current Machine 2.0?",
    .prompt_zh = "（22）下面哪句最符合当前 Machine 2.0 里的 goto？",
    .choices_en = {"A. It jumps to a label statement inside a block.", "B. It always jumps to another file.", "C. It can only be used in module definitions."},
    .choices_zh = {"A. 它会跳到块内部的 label 语句。", "B. 它总是跳到另一个文件。", "C. 它只能在 module 定义里使用。"},
    .correct_index = 0,
    .explain_en = "goto targets a label within the current control flow region, not another file or module-only space.",
    .explain_zh = "goto 的目标是当前控制流区域里的 label，不是另一个文件，也不是只在 module 内使用。",
  },
  {
    .prompt_en = "(23) For raw pointer-offset work, which extra preparation is usually needed?",
    .prompt_zh = "（23）对于原始指针偏移操作，通常还需要什么准备？",
    .choices_en = {"A. only bin.runtime", "B. unsafe.enable and often an unsafe: block", "C. no extra syntax at all"},
    .choices_zh = {"A. 只要 bin.runtime", "B. unsafe.enable，而且很多场景还要 unsafe: 块", "C. 完全不需要额外语法"},
    .correct_index = 1,
    .explain_en = "Current Machine 2.0 treats several pointer raw-memory helpers as unsafe builtins, so unsafe.enable and an unsafe: block are often required.",
    .explain_zh = "当前 Machine 2.0 会把不少指针原始内存 helper 当成 unsafe builtin，因此常常需要 unsafe.enable 和 unsafe: 块。",
  },
  {
    .prompt_en = "(24) Which builtin allocates raw bytes of memory?",
    .prompt_zh = "（24）哪个 builtin 用于分配原始字节内存？",
    .choices_en = {"A. alloc_bytes", "B. make_ptr", "C. ptr_new"},
    .choices_zh = {"A. alloc_bytes", "B. make_ptr", "C. ptr_new"},
    .correct_index = 0,
    .explain_en = "alloc_bytes is the raw allocator used in the lessons.",
    .explain_zh = "课程里用于原始分配的就是 alloc_bytes。",
  },
  {
    .prompt_en = "(25) Which builtin releases memory previously obtained from alloc_bytes?",
    .prompt_zh = "（25）哪个 builtin 用于释放之前由 alloc_bytes 得到的内存？",
    .choices_en = {"A. delete_ptr", "B. free_mem", "C. drop_bytes"},
    .choices_zh = {"A. delete_ptr", "B. free_mem", "C. drop_bytes"},
    .correct_index = 1,
    .explain_en = "free_mem is the matching release helper used in current Machine lessons.",
    .explain_zh = "当前 Machine 课程里与之配套的释放 helper 是 free_mem。",
  },
  {
    .prompt_en = "(26) Which builtin stores a 64-bit integer into memory?",
    .prompt_zh = "（26）哪个 builtin 用于向内存写入 64 位整数？",
    .choices_en = {"A. write_i64", "B. store_i64", "C. mem_i64"},
    .choices_zh = {"A. write_i64", "B. store_i64", "C. mem_i64"},
    .correct_index = 1,
    .explain_en = "store_i64 writes a 64-bit integer to a pointer location.",
    .explain_zh = "store_i64 用于向某个指针位置写入 64 位整数。",
  },
  {
    .prompt_en = "(27) Which builtin reads a 64-bit integer from memory?",
    .prompt_zh = "（27）哪个 builtin 用于从内存读取 64 位整数？",
    .choices_en = {"A. load_i64", "B. read_i64", "C. fetch_i64"},
    .choices_zh = {"A. load_i64", "B. read_i64", "C. fetch_i64"},
    .correct_index = 0,
    .explain_en = "load_i64 reads a 64-bit integer from a pointer location.",
    .explain_zh = "load_i64 用于从某个指针位置读取 64 位整数。",
  },
  {
    .prompt_en = "(28) Which statement is correct about ptr_offset in your current compiler?",
    .prompt_zh = "（28）根据你当前这版编译器，关于 ptr_offset 哪句是正确的？",
    .choices_en = {"A. It is safe anywhere.", "B. It needs unsafe.enable and must appear inside an unsafe: block.", "C. It only works in baremetal mode."},
    .choices_zh = {"A. 它在任何地方都是安全的。", "B. 它需要 unsafe.enable，而且必须出现在 unsafe: 块里。", "C. 它只能在 baremetal 模式下工作。"},
    .correct_index = 1,
    .explain_en = "Your recent compiler errors showed exactly that ptr_offset must be in an unsafe: block after unsafe.enable is enabled.",
    .explain_zh = "你前面的真实编译报错已经证明：ptr_offset 在开启 unsafe.enable 后，还必须写在 unsafe: 块里。",
  },
  {
    .prompt_en = "(29) Which statement is correct about ptr_to_i64 / ptr_from_i64 in your current compiler?",
    .prompt_zh = "（29）根据你当前这版编译器，关于 ptr_to_i64 / ptr_from_i64 哪句是正确的？",
    .choices_en = {"A. They are safe builtins.", "B. They need unsafe.enable and must appear inside unsafe: blocks.", "C. They require bin.runtime only."},
    .choices_zh = {"A. 它们是安全 builtin。", "B. 它们需要 unsafe.enable，而且必须出现在 unsafe: 块里。", "C. 它们只需要 bin.runtime。"},
    .correct_index = 1,
    .explain_en = "Your latest compiler output showed they also must appear inside unsafe: blocks.",
    .explain_zh = "你最新贴出的编译器输出已经显示，它们也必须出现在 unsafe: 块里。",
  },
  {
    .prompt_en = "(30) Which directive enables unsafe builtins globally for the file?",
    .prompt_zh = "（30）哪个指令用于在整个文件层面开启 unsafe builtin 权限？",
    .choices_en = {"A. unsafe.enable", "B. unsafe:", "C. backend.unsafe"},
    .choices_zh = {"A. unsafe.enable", "B. unsafe:", "C. backend.unsafe"},
    .correct_index = 0,
    .explain_en = "unsafe.enable turns on permission for unsafe builtins at the file level. unsafe: is the code block used for actual unsafe operations.",
    .explain_zh = "unsafe.enable 用于在文件层面打开 unsafe builtin 权限；unsafe: 则是承载具体危险操作的代码块。",
  },
  {
    .prompt_en = "(31) Which code block marks the lines that are intentionally unsafe?",
    .prompt_zh = "（31）哪个代码块用于标记这些行是有意进入 unsafe 区域的？",
    .choices_en = {"A. danger:", "B. unsafe:", "C. raw:"},
    .choices_zh = {"A. danger:", "B. unsafe:", "C. raw:"},
    .correct_index = 1,
    .explain_en = "unsafe: is the current block form for intentionally unsafe operations.",
    .explain_zh = "当前用于有意进入危险操作区的块形式是 unsafe:。",
  },
  {
    .prompt_en = "(32) What does this output?\nmain:\n  var i: i64 = 0\n  while i < 3:\n    print i\n    i = i + 1\n  ret 0",
    .prompt_zh = "（32）下面这段代码会输出什么？\nmain:\n  var i: i64 = 0\n  while i < 3:\n    print i\n    i = i + 1\n  ret 0",
    .choices_en = {"A. 0 1 2", "B. 1 2 3", "C. 0 1 2 3"},
    .choices_zh = {"A. 0 1 2", "B. 1 2 3", "C. 0 1 2 3"},
    .correct_index = 0,
    .explain_en = "The loop starts at 0 and stops before 3, so it prints 0, 1, and 2.",
    .explain_zh = "循环从 0 开始，并且在 3 之前停止，所以会打印 0、1、2。",
  },
  {
    .prompt_en = "(33) Which statement about module calls is correct?",
    .prompt_zh = "（33）关于 module 调用，哪句是正确的？",
    .choices_en = {"A. You call functions with ModuleName.functionName(...)", "B. Modules can only store constants", "C. Module calls require goto"},
    .choices_zh = {"A. 你通过 ModuleName.functionName(...) 来调用函数", "B. module 只能存常量", "C. module 调用必须依赖 goto"},
    .correct_index = 0,
    .explain_en = "Modules are used to group related functions, and you call them through dot access.",
    .explain_zh = "module 常用于分组相关函数，并通过点号调用。",
  },
  {
    .prompt_en = "(34) Which builtins are commonly used for dynamic array lessons?",
    .prompt_zh = "（34）动态数组课程里常见的一组 builtin 是哪一组？",
    .choices_en = {"A. array_new / array_push / array_get", "B. ptr_new / ptr_add / ptr_read", "C. fd_open / fd_read / fd_close"},
    .choices_zh = {"A. array_new / array_push / array_get", "B. ptr_new / ptr_add / ptr_read", "C. fd_open / fd_read / fd_close"},
    .correct_index = 0,
    .explain_en = "array_new, array_push, and array_get are core dynamic-array helpers.",
    .explain_zh = "array_new、array_push、array_get 是动态数组里的核心 helper。",
  },
  {
    .prompt_en = "(35) Which builtins are commonly used for list lessons?",
    .prompt_zh = "（35）链表/列表课程里常见的一组 builtin 是哪一组？",
    .choices_en = {"A. list_new / list_push_back / list_get", "B. map_new / map_put / map_get", "C. box_new / box_push / box_get"},
    .choices_zh = {"A. list_new / list_push_back / list_get", "B. map_new / map_put / map_get", "C. box_new / box_push / box_get"},
    .correct_index = 0,
    .explain_en = "The current list container helpers are named list_...",
    .explain_zh = "当前列表容器 helper 使用 list_... 这一组名字。",
  },
  {
    .prompt_en = "(36) Which statement about comments is correct in the current syntax definition?",
    .prompt_zh = "（36）关于当前语法里的注释，哪句是正确的？",
    .choices_en = {"A. Line comments start with --", "B. Line comments start with //", "C. Only block comments exist"},
    .choices_zh = {"A. 行注释以 -- 开始", "B. 行注释以 // 开始", "C. 只有块注释"},
    .correct_index = 0,
    .explain_en = "The current language-spec and lessons use -- as the line comment starter.",
    .explain_zh = "当前语言定义和课程里都使用 -- 作为行注释起始。",
  },
  {
    .prompt_en = "(37) Which directive family selects compilation targets?",
    .prompt_zh = "（37）哪一类指令用于选择编译目标？",
    .choices_en = {"A. target.*", "B. lesson.*", "C. build.*"},
    .choices_zh = {"A. target.*", "B. lesson.*", "C. build.*"},
    .correct_index = 0,
    .explain_en = "The target.* directives are used for selecting freestanding, baremetal, and related targets.",
    .explain_zh = "target.* 指令用来选择 freestanding、baremetal 等目标。",
  },
  {
    .prompt_en = "(38) Which directive family selects code generation backend?",
    .prompt_zh = "（38）哪一类指令用于选择代码生成后端？",
    .choices_en = {"A. backend.*", "B. output.*", "C. codegen.* only in examples"},
    .choices_zh = {"A. backend.*", "B. output.*", "C. 只有示例里才有 codegen.*"},
    .correct_index = 0,
    .explain_en = "backend.* directives are the backend selectors in current Machine 2.0.",
    .explain_zh = "当前 Machine 2.0 里用于选择后端的是 backend.* 指令。",
  },
  {
    .prompt_en = "(39) Which one is a reasonable first step before baremetal lessons?",
    .prompt_zh = "（39）在开始 baremetal 课程前，哪一步更合理？",
    .choices_en = {"A. Learn normal hosted output and control flow first.", "B. Start with APIC immediately and skip syntax basics.", "C. Only study icon design."},
    .choices_zh = {"A. 先学普通 hosted 输出与控制流。", "B. 一上来就直接 APIC，跳过语法基础。", "C. 只研究图标设计。"},
    .correct_index = 0,
    .explain_en = "A staged path is better: normal hosted basics first, then raw memory and targets, then baremetal experiments.",
    .explain_zh = "循序渐进更合理：先 hosted 基础，再原始内存与 target，最后 baremetal 实验。",
  },
  {
    .prompt_en = "(40) Which code is correct for a label inside main in current Machine lessons?",
    .prompt_zh = "（40）在当前 Machine 课程里，下面哪个是 main 内合法的 label 写法？",
    .choices_en = {"A. label loop:", "B. ::loop::", "C. loop:"},
    .choices_zh = {"A. label loop:", "B. ::loop::", "C. loop:"},
    .correct_index = 0,
    .explain_en = "The lessons use label name: as the label statement form, placed inside a block such as main:.",
    .explain_zh = "课程里使用的 label 语句形式是 label 名字:，并且要写在 main: 这类块内部。",
  },
  {
    .prompt_en = "(41) What is the main reason to use ret 0 at the end of beginner examples?",
    .prompt_zh = "（41）为什么在初学示例结尾常常写 ret 0？",
    .choices_en = {"A. It shows normal successful termination clearly.", "B. It turns every value into zero.", "C. It disables syntax highlighting."},
    .choices_zh = {"A. 它能清楚表示程序正常成功结束。", "B. 它会把所有值都变成 0。", "C. 它会关闭语法高亮。"},
    .correct_index = 0,
    .explain_en = "ret 0 clearly communicates a successful program end in beginner lessons.",
    .explain_zh = "在初学关卡里，ret 0 能非常明确地表达“程序成功结束”。",
  },
  {
    .prompt_en = "(42) Which pair of builtins can show pointer addresses in alternate formats?",
    .prompt_zh = "（42）哪一对 builtin 可以把内存地址显示成其他格式？",
    .choices_en = {"A. ptr_hex / ptr_bin", "B. addr_text / addr_bits", "C. hex_ptr / bin_ptr"},
    .choices_zh = {"A. ptr_hex / ptr_bin", "B. addr_text / addr_bits", "C. hex_ptr / bin_ptr"},
    .correct_index = 0,
    .explain_en = "The current builtin list includes ptr_hex and ptr_bin.",
    .explain_zh = "当前 builtin 列表里包含 ptr_hex 和 ptr_bin。",
  },
  {
    .prompt_en = "(43) Which statement best describes the '选择题' node you are adding now?",
    .prompt_zh = "（43）你现在新增的“选择题”节点，哪句描述最准确？",
    .choices_en = {"A. 50 questions, 2 points each, total 100 points.", "B. 10 questions, 10 points each, total 100 points.", "C. Unlimited questions without scoring."},
    .choices_zh = {"A. 50 题，每题 2 分，总分 100 分。", "B. 10 题，每题 10 分，总分 100 分。", "C. 题目无限且不计分。"},
    .correct_index = 0,
    .explain_en = "This node is designed as 50 questions × 2 points = 100 points total.",
    .explain_zh = "这个节点就是按 50 题 × 每题 2 分 = 总分 100 分来设计的。",
  },
  {
    .prompt_en = "(44) Which answer should enable the submit button in the quiz node?",
    .prompt_zh = "（44）在选择题节点里，什么时候提交按钮才应该可点？",
    .choices_en = {"A. After the user answers all 50 questions.", "B. After the user answers any 1 question.", "C. It should always be enabled from the start."},
    .choices_zh = {"A. 用户做完全部 50 题之后。", "B. 用户只做任意 1 题之后。", "C. 从一开始就一直可点。"},
    .correct_index = 0,
    .explain_en = "The requested behavior is to enable submit only after all 50 questions are answered.",
    .explain_zh = "你要求的行为是：必须全部 50 题都做完，提交按钮才能点。",
  },
  {
    .prompt_en = "(45) Which statement is correct about the Settings Panel language change?",
    .prompt_zh = "（45）关于设置面板里的语言切换，哪句是正确的？",
    .choices_en = {"A. It should apply immediately without restarting the app.", "B. It should only apply after rebooting Linux.", "C. It should change only the database path text."},
    .choices_zh = {"A. 应该立即生效，不需要重启应用。", "B. 必须重启 Linux 才生效。", "C. 只会改变数据库路径文字。"},
    .correct_index = 0,
    .explain_en = "The settings change is supposed to refresh the interface immediately.",
    .explain_zh = "设置改动应该立即刷新整个界面。",
  },
  {
    .prompt_en = "(46) Which statement is correct about the title-bar control tooltips?",
    .prompt_zh = "（46）关于标题栏控制按钮提示，哪句是正确的？",
    .choices_en = {"A. They should switch language together with the UI.", "B. They should stay Chinese forever.", "C. They should disappear completely."},
    .choices_zh = {"A. 它们应该随着界面语言一起切换。", "B. 它们应该永远保持中文。", "C. 它们应该彻底消失。"},
    .correct_index = 0,
    .explain_en = "The requested behavior is to localize the tooltips immediately after switching UI language.",
    .explain_zh = "你要求的是：切换界面语言后，这些提示也要立刻本地化。",
  },
  {
    .prompt_en = "(47) Which statement best matches the current editor goal?",
    .prompt_zh = "（47）下面哪句最符合当前编辑器的目标？",
    .choices_en = {"A. Match the Machine Vim highlighting as closely as possible, now done directly in C.", "B. Never show any syntax color at all.", "C. Highlight only comments."},
    .choices_zh = {"A. 尽量贴近 Machine 的 Vim 语法高亮，而且现在直接由 C 代码完成。", "B. 永远不显示任何语法颜色。", "C. 只高亮注释。"},
    .correct_index = 0,
    .explain_en = "The requested target is a direct C-side syntax coloring approach that mirrors the installed Machine Vim groups as closely as practical.",
    .explain_zh = "你要求的目标是：直接在 C 侧做语法着色，并尽量贴近已安装的 Machine Vim 分组。",
  },
  {
    .prompt_en = "(48) Which answer best describes benchmark lessons such as compile speed or run speed?",
    .prompt_zh = "（48）像编译速率、运行速率这样的性能关卡，哪句描述更准确？",
    .choices_en = {"A. They should report timing and whether the threshold was reached.", "B. They should ignore all timing data.", "C. They should only show a random color."},
    .choices_zh = {"A. 它们应该报告耗时并指出是否达到门槛。", "B. 它们应该忽略所有计时数据。", "C. 它们只显示随机颜色。"},
    .correct_index = 0,
    .explain_en = "Benchmark nodes are supposed to measure timing and compare it against a target.",
    .explain_zh = "性能关卡本来就应该测量耗时，并与目标门槛比较。",
  },
  {
    .prompt_en = "(49) Which learning order is most reasonable?",
    .prompt_zh = "（49）哪种学习顺序更合理？",
    .choices_en = {"A. Unlabeled basics -> Normal -> Hard -> Extreme -> Advanced", "B. Advanced first, basics last", "C. Random order every launch"},
    .choices_zh = {"A. 无标签基础 -> 普通 -> 困难 -> 超难 -> 进阶", "B. 先学进阶，最后再学基础", "C. 每次启动都随机顺序"},
    .correct_index = 0,
    .explain_en = "That ordering matches the node-sorting rule you requested for the sidebar.",
    .explain_zh = "这正好对应你为左侧课程树要求的排序规则。",
  },
  {
    .prompt_en = "(50) If a wrong quiz answer is submitted, what should the result include?",
    .prompt_zh = "（50）如果用户提交了错误答案，结果里应该包含什么？",
    .choices_en = {"A. The wrong question number, why it is wrong, and what the correct answer is.", "B. Only a sad face emoji.", "C. No explanation at all."},
    .choices_zh = {"A. 错题题号、为什么错、正确答案是什么。", "B. 只给一个难过表情。", "C. 完全不给解释。"},
    .correct_index = 0,
    .explain_en = "The requested behavior is to show the score plus detailed feedback for wrong answers, including why the selected answer was wrong and which answer is correct.",
    .explain_zh = "你要求的是：提交后不仅给分，还要指出错题编号、为什么错、正确答案是什么。",
  },
};

const QuizQuestion *app_quiz_questions(gsize *count_out) {
  if (count_out) { *count_out = G_N_ELEMENTS(QUESTIONS); }
  return QUESTIONS;
}
